#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Manager.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Shared/_Layout.cshtml")]
    public class Layout : Piranha.Manager.Templates.ManagerLayoutPage
    {

                // Resolve package relative syntax
                // Also, if it comes from a static embedded resource, change the path accordingly
                public override string Href(string virtualPath, params object[] pathParts) {
                    virtualPath = ApplicationPart.ProcessVirtualPath(GetType().Assembly, VirtualPath, virtualPath);
                    return base.Href(virtualPath, pathParts);
                }
        public Layout()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta http-equiv=\"content-type\" content=\"tex" +
"t/html; charset=utf-8\"/>\r\n    <meta name=\"viewport\" content=\"width=device-width," +
" initial-scale=1.0, maximum-scale=1.0\">\r\n\r\n    <title>");


            
            #line 10 "..\..\Shared\_Layout.cshtml"
      Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n    <link rel=\"icon\" href=\"");


            
            #line 12 "..\..\Shared\_Layout.cshtml"
                      Write(Manager.Href("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\">\r\n    <link rel=\"shortcut icon\" href=\"");


            
            #line 13 "..\..\Shared\_Layout.cshtml"
                               Write(Manager.Href("~/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"image/x-icon\"> \r\n    <link href=\"");


            
            #line 14 "..\..\Shared\_Layout.cshtml"
           Write(Manager.Href("~/content/css/ext/chosen.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n    <link href=\"");


            
            #line 15 "..\..\Shared\_Layout.cshtml"
           Write(Manager.Href("~/content/css/ext/jquery-ui-1.9.2.custom.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <link href=\"");


            
            #line 16 "..\..\Shared\_Layout.cshtml"
           Write(Manager.Href("~/content/css/style.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n    <link href=\"");


            
            #line 17 "..\..\Shared\_Layout.cshtml"
           Write(Manager.Href("~/content/css/theme.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 19 "..\..\Shared\_Layout.cshtml"
                                   Write(Manager.Href("~/content/js/ext/jquery-1.7.2.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 20 "..\..\Shared\_Layout.cshtml"
                                   Write(Manager.Href("~/content/js/jquery.manager.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 21 "..\..\Shared\_Layout.cshtml"
                                   Write(Manager.Href("~/content/js/ext/chosen.jquery.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\">\r\n        var siteroot = \"");


            
            #line 23 "..\..\Shared\_Layout.cshtml"
                   Write(Href("~/"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        ");



WriteLiteral(@"
        siteroot += !siteroot.endsWith(""/"") ? ""/"" : """";

        $(document).ready(function () {
            $("".message"").click(function () { $(this).fadeOut(""medium""); });

            $("".chzn-select"").chosen().trigger(""liszt:updated"");
        });
    </script>
");


            
            #line 33 "..\..\Shared\_Layout.cshtml"
     if (!String.IsNullOrEmpty(Page.Message)) {

            
            #line default
            #line hidden
WriteLiteral("    <script type=\"text/javascript\">\r\n        setTimeout(function () {\r\n          " +
"  $(\".sys-message\").slideUp();\r\n        }, 2000);\r\n    </script>\r\n");


            
            #line 39 "..\..\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 40 "..\..\Shared\_Layout.cshtml"
Write(RenderSection("Head", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div class=\"top\">\r\n        <div class=\"container_12\">\r\n   " +
"         <div class=\"grid_12 header\">\r\n                <a class=\"home\" href=\"");


            
            #line 46 "..\..\Shared\_Layout.cshtml"
                                 Write(Manager.Href("~/"));

            
            #line default
            #line hidden
WriteLiteral("\"></a>\r\n                <a class=\"public-site\" target=\"preview\" href=\"http://");


            
            #line 47 "..\..\Shared\_Layout.cshtml"
                                                                Write(Request.Url.DnsSafeHost);

            
            #line default
            #line hidden

            
            #line 47 "..\..\Shared\_Layout.cshtml"
                                                                                        Write(Href("~/"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    ");


            
            #line 48 "..\..\Shared\_Layout.cshtml"
               Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                ");



WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"title\">\r\n      " +
"  <div class=\"container_12\">\r\n            <div class=\"grid_12\"><h1>");


            
            #line 55 "..\..\Shared\_Layout.cshtml"
                                Write(Page.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1></div>\r\n        </div>\r\n    </div>\r\n    <div class=\"body\">\r\n        <div cla" +
"ss=\"container_12\">\r\n            <div class=\"grid_12 toolbar-container\">\r\n       " +
"         ");


            
            #line 61 "..\..\Shared\_Layout.cshtml"
           Write(RenderSection("Toolbar", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 63 "..\..\Shared\_Layout.cshtml"
             if (!String.IsNullOrEmpty(Page.Message)) {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid_12 sys-message\">\r\n                <div class=\"box");


            
            #line 65 "..\..\Shared\_Layout.cshtml"
                           Write(!String.IsNullOrEmpty(Page.MessageCss) ? " " + Page.MessageCss : "");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    <div class=\"inner\">\r\n                        <div class=\"" +
"ico\"></div><p>");


            
            #line 67 "..\..\Shared\_Layout.cshtml"
                                             Write(Page.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");


            
            #line 71 "..\..\Shared\_Layout.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"content left\">\r\n                ");


            
            #line 73 "..\..\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
            </div>
        </div>
    </div>
    <div id=""boxSysMsg"" class=""floatbox"">
        <div class=""bg""></div>
        <div class=""box"">
            <div class=""title""><h2 id=""SysMsgTitle""></h2></div>
            <div class=""inner"">
                <p id=""SysMsgBody""></p>
            </div>
        </div>
    </div>
    ");


            
            #line 86 "..\..\Shared\_Layout.cshtml"
Write(RenderSection("Foot", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
