#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Manager.User
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/User/Edit.cshtml")]
    public class Edit : Piranha.Manager.Templates.UserEdit
    {

                // Resolve package relative syntax
                // Also, if it comes from a static embedded resource, change the path accordingly
                public override string Href(string virtualPath, params object[] pathParts) {
                    virtualPath = ApplicationPart.ProcessVirtualPath(GetType().Assembly, VirtualPath, virtualPath);
                    return base.Href(virtualPath, pathParts);
                }
        public Edit()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



            
            #line 4 "..\..\User\Edit.cshtml"
  
    Layout = "~/Manager/Shared/_Layout.cshtml" ;


            
            #line default
            #line hidden

DefineSection("Toolbar", () => {

WriteLiteral("\r\n");



WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a class=\"save submit\">");


            
            #line 12 "..\..\User\Edit.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 13 "..\..\User\Edit.cshtml"
             if (Model.User.Id != Guid.Empty) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 14 "..\..\User\Edit.cshtml"
                    Write(Href("~/manager/user/edit/delete/" + Model.User.Id));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 14 "..\..\User\Edit.cshtml"
                                                                                         Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 15 "..\..\User\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 16 "..\..\User\Edit.cshtml"
                    Write(Href("~/manager/user"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 16 "..\..\User\Edit.cshtml"
                                                          Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 17 "..\..\User\Edit.cshtml"
             if (Model.User.Id != Guid.Empty) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 18 "..\..\User\Edit.cshtml"
                    Write(Href("~/manager/user/edit/" + Model.User.Id));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 18 "..\..\User\Edit.cshtml"
                                                                                   Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 19 "..\..\User\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n");


});

WriteLiteral("\r\n");


DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 26 "..\..\User\Edit.cshtml"
                                   Write(Href("~/manager/content/js/ext/jquery-ui-1.9.2.custom.min.js"));

            
            #line default
            #line hidden
WriteLiteral(@"""></script>
    <script type=""text/javascript"">
        function disableLockedUntil() {
            $('#User_LockedUntil').val('').attr('disabled', true);
        }
        function enableLockedUntil() {
            $('#User_LockedUntil').val('').removeAttr('disabled');
        }

        $(document).ready(function () {
            if (!$('#User_IsLocked').is(':checked')) {
                disableLockedUntil();
            }
            $('#User_IsLocked').click(function () {
                if (!$(this).is(':checked'))
                    disableLockedUntil();
                else enableLockedUntil();
            });
            $('.datepicker input').datepicker({
                dateFormat: ""yy-mm-dd""
            });
        });
    </script>
");


});

WriteLiteral("\r\n<form method=\"post\">\r\n");


            
            #line 51 "..\..\User\Edit.cshtml"
Write(UI.FormAction("Save"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 52 "..\..\User\Edit.cshtml"
Write(Html.Hidden("m.User.Id", Model.User.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid_9\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 55 "..\..\User\Edit.cshtml"
                          Write(Piranha.Resources.Settings.UserInfo);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 59 "..\..\User\Edit.cshtml"
               Write(Html.Label(@Piranha.Resources.Settings.Login));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 61 "..\..\User\Edit.cshtml"
                   Write(Form.TextBoxFor(m => m.User.Login));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 62 "..\..\User\Edit.cshtml"
               Write(Html.ValidationMessage("m.User.Login"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 65 "..\..\User\Edit.cshtml"
               Write(Html.Label(@Piranha.Resources.Settings.Firstname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 67 "..\..\User\Edit.cshtml"
                   Write(Form.TextBoxFor(m => m.User.Firstname));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 68 "..\..\User\Edit.cshtml"
               Write(Html.ValidationMessage("m.User.Firstname"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 71 "..\..\User\Edit.cshtml"
               Write(Html.Label(@Piranha.Resources.Settings.Surname));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 73 "..\..\User\Edit.cshtml"
                   Write(Form.TextBoxFor(m => m.User.Surname));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 74 "..\..\User\Edit.cshtml"
               Write(Html.ValidationMessage("m.User.Surname"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 77 "..\..\User\Edit.cshtml"
               Write(Html.Label(@Piranha.Resources.Settings.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 79 "..\..\User\Edit.cshtml"
                   Write(Form.TextBoxFor(m => m.User.Email));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 80 "..\..\User\Edit.cshtml"
               Write(Html.ValidationMessage("m.User.Email"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 83 "..\..\User\Edit.cshtml"
               Write(Html.Label(@Piranha.Resources.Settings.GroupName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 85 "..\..\User\Edit.cshtml"
                   Write(Html.DropDownList("m.User.GroupId", Model.Groups, Model.User.GroupId));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n   " +
" <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 91 "..\..\User\Edit.cshtml"
                          Write(Piranha.Resources.Settings.Account);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 94 "..\..\User\Edit.cshtml"
               Write(Html.Label(@Piranha.Resources.Settings.Locked));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <p>");


            
            #line 95 "..\..\User\Edit.cshtml"
                  Write(Form.CheckBoxFor(m => m.User.IsLocked));

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 95 "..\..\User\Edit.cshtml"
                                                           Write(Piranha.Resources.Settings.LockedInfo);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                </li>\r\n                ");



WriteLiteral("\r\n            </ul>\r\n        </div>\r\n    </div>\r\n    ");



WriteLiteral("\r\n</div>\r\n<div class=\"grid_3\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"" +
"><h2>");


            
            #line 110 "..\..\User\Edit.cshtml"
                           Write(Model.User.Id == Guid.Empty ? @Piranha.Resources.Settings.CreatePassword : @Piranha.Resources.Settings.ChangePassword);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 114 "..\..\User\Edit.cshtml"
               Write(Html.Label(@Piranha.Resources.Global.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 116 "..\..\User\Edit.cshtml"
                   Write(Html.Password("m.Password.Password"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 119 "..\..\User\Edit.cshtml"
               Write(Html.Label(@Piranha.Resources.Global.Confirm));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 121 "..\..\User\Edit.cshtml"
                   Write(Html.Password("m.Password.PasswordConfirm"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 122 "..\..\User\Edit.cshtml"
               Write(Html.ValidationMessage("m.Password.PasswordConfirm"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n<" +
"/form>");


        }
    }
}
#pragma warning restore 1591
