#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Manager.PostType
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/PostType/Index.cshtml")]
    public class Index : Piranha.WebPages.ContentPage<Piranha.Manager.Models.PostTypeListModel>
    {

                // Resolve package relative syntax
                // Also, if it comes from a static embedded resource, change the path accordingly
                public override string Href(string virtualPath, params object[] pathParts) {
                    virtualPath = ApplicationPart.ProcessVirtualPath(GetType().Assembly, VirtualPath, virtualPath);
                    return base.Href(virtualPath, pathParts);
                }
        public Index()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



            
            #line 4 "..\..\PostType\Index.cshtml"
  
    Page.Title = @Piranha.Manager.Resources.PostType.ListTitle ;
    Layout = "~/Manager/Shared/_Layout.cshtml" ;


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n        $(document).ready(function() {\r\n  " +
"          $(\".delete\").click(function() {\r\n                return confirm(\"");


            
            #line 12 "..\..\PostType\Index.cshtml"
                           Write(Piranha.Manager.Resources.PostType.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral(@""") ;
            });

            var options = {
                listClass:  'list-js',
                searchId: 'search',
                valueNames: ['name', 'created', 'updated']
            };
            new List('list', options);
        });
    </script>
");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral(" \r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li>" +
"<a href=\"");


            
            #line 28 "..\..\PostType\Index.cshtml"
                    Write(Href("~/manager/posttype/edit"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"add\">");


            
            #line 28 "..\..\PostType\Index.cshtml"
                                                                  Write(Piranha.Manager.Resources.Toolbar.Add);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 29 "..\..\PostType\Index.cshtml"
                    Write(Href("~/manager/posttype"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 29 "..\..\PostType\Index.cshtml"
                                                                 Write(Piranha.Manager.Resources.Toolbar.Reload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <button class=\"search\" title=\"");


            
            #line 31 "..\..\PostType\Index.cshtml"
                                 Write(Piranha.Manager.Resources.Toolbar.Search);

            
            #line default
            #line hidden
WriteLiteral("\"></button>");


            
            #line 31 "..\..\PostType\Index.cshtml"
                                                                                     Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n    <table id=\"list\" class=\"list\">\r\n        <thead>\r\n   " +
"         <tr>\r\n                <th><span class=\"sort asc\" data-sort=\"name\">");


            
            #line 40 "..\..\PostType\Index.cshtml"
                                                       Write(Piranha.Manager.Resources.Global.Name);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th><span class=\"sort\" data-sort=\"created\">");


            
            #line 41 "..\..\PostType\Index.cshtml"
                                                      Write(Piranha.Manager.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th><span class=\"sort\" data-sort=\"updated\">");


            
            #line 42 "..\..\PostType\Index.cshtml"
                                                      Write(Piranha.Manager.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th></th>\r\n            </tr>\r\n        </thead>\r\n   " +
"     <tbody class=\"list-js\">\r\n");


            
            #line 47 "..\..\PostType\Index.cshtml"
             foreach (var pt in Model.Templates) {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td class=\"name\"><a href=\"");


            
            #line 49 "..\..\PostType\Index.cshtml"
                                     Write(Href("~/manager/posttype/edit/" + pt.Id));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 49 "..\..\PostType\Index.cshtml"
                                                                                Write(pt.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td class=\"created date\">");


            
            #line 50 "..\..\PostType\Index.cshtml"
                                    Write(pt.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"updated date\">");


            
            #line 51 "..\..\PostType\Index.cshtml"
                                    Write(pt.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"buttons one\">\r\n                    <a class=\"ic" +
"on delete\" title=\"");


            
            #line 53 "..\..\PostType\Index.cshtml"
                                             Write(Piranha.Manager.Resources.PostType.ListDelete);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"");


            
            #line 53 "..\..\PostType\Index.cshtml"
                                                                                                   Write(Href("~/manager/posttype/edit/delete/" + pt.Id));

            
            #line default
            #line hidden
WriteLiteral("\"></a></td>\r\n            </tr>\r\n");


            
            #line 55 "..\..\PostType\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
