#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Post
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    using Piranha.Areas.Manager.Models;
    
    #line default
    #line hidden
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Post/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Piranha.Areas.Manager.Models.PostListModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
DefineSection("Head", () => {

WriteLiteral("\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        .content .tabs {\r\n            float: left;\r\n            margin-left: 1" +
"0px;\r\n        }\r\n        .content .tabs .selected {\r\n            border: 0 none;" +
"\r\n            padding: 10px 20px 6px;\r\n        }\r\n    </style>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(document).ready(function () {
            // Set the selected template id
            $("".templates"").click(function () {
                $(""#TemplateId"").val($(this).attr(""data-templateid""));
                $(""form"").submit();
            });

            // Notification before delete
            $("".delete"").click(function() {
                return confirm(""");

            
            #line 24 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                           Write(Piranha.Resources.Post.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral(@""") ;
            });

            // Setup post list
            var options = {
                listClass:  'list-js',
                searchId: 'search',
                valueNames: ['title', 'template', 'updated', 'created']
            };
            var postList = new List('list', options);
        });
    </script>
");

});

DefineSection("Toolbar", () => {

WriteLiteral(" \r\n");

            
            #line 38 "..\..\Areas\Manager\Views\Post\Index.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n        <ul>\r\n            <li><a");

WriteLiteral(" onclick=\"floatBox.show(\'boxTemplates\')\"");

WriteLiteral(" class=\"add\"");

WriteLiteral(">");

            
            #line 42 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                  Write(Piranha.Resources.Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a");

WriteLiteral(" href=\"\"");

WriteLiteral(" class=\"refresh\"");

WriteLiteral(">");

            
            #line 43 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                      Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Areas\Manager\Views\Post\Index.cshtml"
       Write(Piranha.WebPages.Hooks.Manager.Toolbar.Render(Url, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n        <button");

WriteLiteral(" class=\"search\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1601), Tuple.Create("\"", 1648)
            
            #line 46 "..\..\Areas\Manager\Views\Post\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1609), Tuple.Create<System.Object, System.Int32>(Piranha.Resources.Global.ToolbarSearch
            
            #line default
            #line hidden
, 1609), false)
);

WriteLiteral("></button>");

            
            #line 46 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                   Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"grid_12\"");

WriteLiteral(">\r\n");

            
            #line 52 "..\..\Areas\Manager\Views\Post\Index.cshtml"
 using (Html.BeginForm("insert", (string)ViewContext.RouteData.Values["Controller"])) {
    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\Manager\Views\Post\Index.cshtml"
Write(Html.Hidden("TemplateId", "906761ea-6c04-4f4b-9365-f2c350ff4372"));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                      
    
            
            #line default
            #line hidden
            
            #line 54 "..\..\Areas\Manager\Views\Post\Index.cshtml"
Write(Html.Hidden("ParentId"));

            
            #line default
            #line hidden
            
            #line 54 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\Manager\Views\Post\Index.cshtml"
Write(Html.Hidden("Seqno"));

            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                         
    if (Model.Templates.Count > 1) {

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <ul");

WriteLiteral(" class=\"tabs\"");

WriteLiteral(">\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2077), Tuple.Create("\"", 2112)
            
            #line 59 "..\..\Areas\Manager\Views\Post\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2084), Tuple.Create<System.Object, System.Int32>(Url.Action("index", "post")
            
            #line default
            #line hidden
, 2084), false)
);

WriteLiteral(" ");

            
            #line 59 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                   Write(Model.ActiveTemplate == Guid.Empty ? "class=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">All</a></li>\r\n");

            
            #line 60 "..\..\Areas\Manager\Views\Post\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 60 "..\..\Areas\Manager\Views\Post\Index.cshtml"
             foreach (var template in Model.Templates) {

            
            #line default
            #line hidden
WriteLiteral("            <li>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2284), Tuple.Create("\"", 2349)
            
            #line 62 "..\..\Areas\Manager\Views\Post\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2291), Tuple.Create<System.Object, System.Int32>(Url.Action("template", "post", new { @id = template.Id })
            
            #line default
            #line hidden
, 2291), false)
);

WriteLiteral(" ");

            
            #line 62 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                 Write(template.Id == Model.ActiveTemplate ? "class=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 62 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                                                                               Write(template.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            </li>\r\n");

            
            #line 64 "..\..\Areas\Manager\Views\Post\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n");

            
            #line 68 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" id=\"list\"");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th><span");

WriteLiteral(" class=\"sort asc\"");

WriteLiteral(" data-sort=\"title\"");

WriteLiteral(">");

            
            #line 72 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                        Write(Piranha.Resources.Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th><span");

WriteLiteral(" class=\"sort\"");

WriteLiteral(" data-sort=\"template\"");

WriteLiteral(">");

            
            #line 73 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                       Write(Piranha.Resources.Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th");

WriteLiteral(" class=\"date\"");

WriteLiteral("><span");

WriteLiteral(" class=\"sort\"");

WriteLiteral(" data-sort=\"updated\"");

WriteLiteral(">");

            
            #line 74 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                   Write(Piranha.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th");

WriteLiteral(" class=\"date\"");

WriteLiteral("><span");

WriteLiteral(" class=\"sort\"");

WriteLiteral(" data-sort=\"created\"");

WriteLiteral(">");

            
            #line 75 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                   Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th");

WriteLiteral(" class=\"one\"");

WriteLiteral("></th>\r\n            </tr>\r\n        </thead>\r\n        <tbody");

WriteLiteral(" class=\"list-js\"");

WriteLiteral(">\r\n");

            
            #line 80 "..\..\Areas\Manager\Views\Post\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 80 "..\..\Areas\Manager\Views\Post\Index.cshtml"
             foreach (var post in Model.Posts) {

            
            #line default
            #line hidden
WriteLiteral("            <tr");

            
            #line 81 "..\..\Areas\Manager\Views\Post\Index.cshtml"
           Write(post.Status == PostListModel.PostStatus.DRAFT || post.Status == PostListModel.PostStatus.UNPUBLISHED ? " class=draft" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n                <td");

WriteLiteral(" class=\"title\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3394), Tuple.Create("\"", 3442)
            
            #line 82 "..\..\Areas\Manager\Views\Post\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3401), Tuple.Create<System.Object, System.Int32>(Url.Action("edit", new { id = post.Id })
            
            #line default
            #line hidden
, 3401), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 83 "..\..\Areas\Manager\Views\Post\Index.cshtml"
               Write(post.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"list-info\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 85 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                   Write(Html.Raw(post.Status == PostListModel.PostStatus.UNPUBLISHED ? "<span class=info-unpublished></span>" : (post.Status == PostListModel.PostStatus.DRAFT ? "<span class=info-draft></span>" : "")));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 86 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 86 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                         if (post.NewComments > 0) {

            
            #line default
            #line hidden
WriteLiteral("                        <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 87 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                              Write(post.NewComments);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 88 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </a></td>\r\n                <td");

WriteLiteral(" class=\"template\"");

WriteLiteral(">");

            
            #line 91 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                Write(post.TemplateName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"updated\"");

WriteLiteral(">");

            
            #line 92 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                               Write(post.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"created\"");

WriteLiteral(">");

            
            #line 93 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                               Write(post.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"buttons\"");

WriteLiteral(">\r\n");

            
            #line 95 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 95 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                     if (User.HasAccess("ADMIN_POST_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4302), Tuple.Create("\"", 4352)
            
            #line 96 "..\..\Areas\Manager\Views\Post\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4309), Tuple.Create<System.Object, System.Int32>(Url.Action("delete", new { id = post.Id })
            
            #line default
            #line hidden
, 4309), false)
);

WriteLiteral(" title=\"Ta bort artikel\"");

WriteLiteral(" class=\"icon delete\"");

WriteLiteral("></a>\r\n");

            
            #line 97 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n");

            
            #line 100 "..\..\Areas\Manager\Views\Post\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n        <tfoot>\r\n            <tr>\r\n                <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral("></td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n");

            
            #line 108 "..\..\Areas\Manager\Views\Post\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

DefineSection("Foot", () => {

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"boxTemplates\"");

WriteLiteral(" class=\"floatbox\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bg\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><a");

WriteLiteral(" class=\"close-btn right\"");

WriteLiteral(" data-id=\"boxTemplates\"");

WriteLiteral("></a><h2>");

            
            #line 115 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                Write(Piranha.Resources.Post.PopupTypeTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n");

            
            #line 117 "..\..\Areas\Manager\Views\Post\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 117 "..\..\Areas\Manager\Views\Post\Index.cshtml"
         foreach (var template in Model.Templates) {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 4985), Tuple.Create("\"", 5056)
, Tuple.Create(Tuple.Create("", 4993), Tuple.Create("templates", 4993), true)
            
            #line 118 "..\..\Areas\Manager\Views\Post\Index.cshtml"
, Tuple.Create(Tuple.Create(" ", 5002), Tuple.Create<System.Object, System.Int32>(Model.Templates.Count > 6 ? "compressed" : ""
            
            #line default
            #line hidden
, 5003), false)
, Tuple.Create(Tuple.Create(" ", 5051), Tuple.Create("left", 5052), true)
);

WriteLiteral(" data-templateid=\"");

            
            #line 118 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                                     Write(template.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                <h3>");

            
            #line 119 "..\..\Areas\Manager\Views\Post\Index.cshtml"
               Write(template.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                <div");

WriteLiteral(" class=\"preview\"");

WriteLiteral(" style=\"width:120px;height:120px;margin:0 auto;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 121 "..\..\Areas\Manager\Views\Post\Index.cshtml"
               Write(template.Preview.Html());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <p>");

            
            #line 123 "..\..\Areas\Manager\Views\Post\Index.cshtml"
              Write(template.Description);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n");

            
            #line 125 "..\..\Areas\Manager\Views\Post\Index.cshtml"
        } 

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n");

});

        }
    }
}
#pragma warning restore 1591
