#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Extend;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Models.Manager.PageModels;
    
    #line default
    #line hidden
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/Edit.cshtml")]
    public partial class _Areas_Manager_Views_Page_Edit_cshtml : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.PageModels.EditModel>
    {
        public _Areas_Manager_Views_Page_Edit_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("Head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 170), Tuple.Create("\"", 226)
, Tuple.Create(Tuple.Create("", 176), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.form.js")
, 176), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 273), Tuple.Create("\"", 332)
, Tuple.Create(Tuple.Create("", 279), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.regions.js")
, 279), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 379), Tuple.Create("\"", 441)
, Tuple.Create(Tuple.Create("", 385), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.attachment.js")
, 385), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 488), Tuple.Create("\"", 552)
, Tuple.Create(Tuple.Create("", 494), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.media.dialog.js")
, 494), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 599), Tuple.Create("\"", 659)
, Tuple.Create(Tuple.Create("", 605), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.comments.js")
, 605), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 706), Tuple.Create("\"", 774)
, Tuple.Create(Tuple.Create("", 712), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/ext/jquery.equalheights.js")
, 712), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("~/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\t\tvar folderId = \"\";\r\n\t\tvar deletemsg = \"");

            
            #line 14 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                    Write(Piranha.Resources.Page.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n        $(document).ready(function () {\r\n            // UI Stuff\r\n         " +
"   $(\"#Page_Title\").focus();\r\n            $(\'.first-row .box\').equalHeights();\r\n" +
"\r\n");

            
            #line 21 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Action == EditModel.ActionType.ATTACHMENTS) {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n            $(\'#btn_attachments\').click();\r\n            ");

WriteLiteral("\r\n");

            
            #line 25 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"
            $(""#Page_ParentId"").change(function () {
                var page_id = $(""#Page_Id"").val();
                var page_parentid = $(""#org_parentid"").val();
                var page_seqno = $(""#Page_Seqno"").val();
                var parentid = $(""#Page_ParentId"").val();
                var site_tree = $(""#Page_SiteTreeInternalId"").val();

                $.get(""");

            
            #line 34 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("siblings"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&page_parentid="" + page_parentid + ""&page_seqno="" + page_seqno + ""&parentid="" + parentid + ""&site_tree="" + site_tree, function (data) {
                    $(""#div-seqno"").html(data);
                });
            });

            $('#Page_GroupId').change(function() {
                var page_id = $(""#Page_Id"").val();
                var group_id = $(this).val();

                $.get(""");

            
            #line 43 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("grouplist"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&group_id="" + group_id, function(data) {
                    $(""#disable-groups"").html(data);
                });
            });

            $('#btnMove').click(function () {
                $('#placement-edit').slideToggle('fast');
                $(this).toggleClass('active');
                return false;
            });

            new piranha.comment('");

            
            #line 54 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            Write(Model.Page.Id);

            
            #line default
            #line hidden
WriteLiteral("\', \'comment-notification\', \'pnl-comments .inner\');\r\n            \r\n            new" +
" piranha.media(\'btn_attach\', \'boxContent\', function (a) {\r\n                // St" +
"ore folder id so we can open the same folder next time.\r\n                folderI" +
"d = a.ParentId;\r\n\r\n                // Add the attachment\r\n                $(\"#tb" +
"l-attachments\").append(\r\n                    \'<tr data-id=\"\' + a.Id + \'\">\' +\r\n  " +
"                      \'<td><img src=\"\' + a.ThumbnailUrl + \'/50\" /></td>\' +\r\n    " +
"                    \'<td>\' + a.DisplayName + \'</td>\' +\r\n                        " +
"\'<td>\' + a.Type + \'</td>\' +\r\n                        \'<td class=\"buttons three\">" +
"\' +\r\n                            \'<a class=\"icon up marg\"></a>\' +\r\n             " +
"               \'<a class=\"icon down marg\"></a>\' +\r\n                            \'" +
"<a class=\"icon delete\"></a></td>\' +\r\n                    \'</tr>\');\r\n            " +
"});\r\n\r\n            $(\".toolbar .delete\").click(function () {\r\n            \tretur" +
"n confirm(deletemsg);\r\n            });\r\n        });\r\n\r\n        //\r\n        // Hi" +
"des all editors on the page. This callback is called from jquery.attachments.js\r" +
"\n        //\r\n        function hideEditors() {\r\n            $(\"#pageregions .inpu" +
"t, #globalregions .input\").hide();\r\n            $(\"#regionbuttons button\").remov" +
"eClass(\"active\");\r\n            $(\"#attachments\").hide();\r\n\r\n            $(\"#regi" +
"ons .region-body\").hide();\r\n            $(\"#regionbuttons button\").removeClass(\"" +
"active\");\r\n            $(\"#attachments\").hide();\r\n        }\r\n\r\n        //\r\n     " +
"   // This callback is called from jquery.attachments.js before form submit.\r\n  " +
"      //\r\n        function addAttachmentData(index, val) {\r\n            $(\"#atta" +
"chment_data\").append(\r\n                    \'<input id=\"Page_Attachments_\' + inde" +
"x +\r\n                    \'_\" name=\"Page.Attachments[\' + index +\r\n               " +
"     \']\" type=\"hidden\" value=\"\' + $(val).attr(\"data-id\") + \'\" />\');\r\n        }\r\n" +
"    </script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Toolbar", () => {

WriteLiteral("\r\n");

            
            #line 104 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n        <ul>\r\n            <li><a");

WriteLiteral(" class=\"save submit\"");

WriteLiteral(">");

            
            #line 108 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSaveDraft);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 109 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            
            
            #line default
            #line hidden
            
            #line 109 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (!Model.Page.IsNew && !Model.Page.IsBlock) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4809), Tuple.Create("\"", 4902)
            
            #line 110 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4816), Tuple.Create<System.Object, System.Int32>(Piranha.WebPages.WebPiranha.GetSiteUrl()
            
            #line default
            #line hidden
, 4816), false)
            
            #line 110 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4857), Tuple.Create<System.Object, System.Int32>(Url.GetPermalink(Model.Page.Permalink, true)
            
            #line default
            #line hidden
, 4857), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(" class=\"preview\"");

WriteLiteral(">");

            
            #line 110 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                             Write(Piranha.Resources.Global.ToolbarPreview);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 111 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 112 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteLiteral(" class=\"publish\"");

WriteLiteral(">");

            
            #line 113 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Model.Page.Published == DateTime.MinValue ? Piranha.Resources.Global.ToolbarPublish : Piranha.Resources.Global.ToolbarUpdate);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 114 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 115 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Page.Published > DateTime.MinValue && !Model.IsSite && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5386), Tuple.Create("\"", 5445)
            
            #line 116 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5393), Tuple.Create<System.Object, System.Int32>(Url.Action("unpublish", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5393), false)
);

WriteLiteral(" class=\"unpublish\"");

WriteLiteral(">");

            
            #line 116 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                            Write(Piranha.Resources.Global.ToolbarUnpublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 117 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 118 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Page.Published > DateTime.MinValue && Model.Page.Updated > Model.Page.LastPublished) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5662), Tuple.Create("\"", 5718)
            
            #line 119 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5669), Tuple.Create<System.Object, System.Int32>(Url.Action("revert", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5669), false)
);

WriteLiteral(" class=\"revert\"");

WriteLiteral(">");

            
            #line 119 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarRevert);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 121 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (!Model.Page.IsNew && Model.CanDelete && !Model.IsSite && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5933), Tuple.Create("\"", 5989)
            
            #line 122 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5940), Tuple.Create<System.Object, System.Int32>(Url.Action("delete", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5940), false)
);

WriteLiteral(" class=\"delete\"");

WriteLiteral(">");

            
            #line 122 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 123 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 124 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (String.IsNullOrEmpty(ViewBag.ReturnUrl)) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6150), Tuple.Create("\"", 6205)
            
            #line 125 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6157), Tuple.Create<System.Object, System.Int32>(Url.Action("index", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 6157), false)
);

WriteLiteral(" class=\"back\"");

WriteLiteral(">");

            
            #line 125 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                   Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 126 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6308), Tuple.Create("\"", 6333)
            
            #line 127 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6315), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnUrl
            
            #line default
            #line hidden
, 6315), false)
);

WriteLiteral(" class=\"back\"");

WriteLiteral(">");

            
            #line 127 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                     Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 128 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6429), Tuple.Create("\"", 6483)
            
            #line 129 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6436), Tuple.Create<System.Object, System.Int32>(Url.Action("edit", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 6436), false)
);

WriteLiteral(" class=\"refresh\"");

WriteLiteral(">");

            
            #line 129 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                     Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

WriteLiteral("            ");

            
            #line 130 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
       Write(Piranha.WebPages.Hooks.Manager.Toolbar.Render(Url, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n");

});

WriteLiteral("\r\n");

            
            #line 137 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.BeginForm("edit", (string)ViewContext.RouteData.Values["Controller"]) ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 139 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 140 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 141 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeInternalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 142 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.OriginalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 143 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 144 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 145 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 146 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.TemplateId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 147 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.PermalinkId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 148 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t");

            
            #line 149 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsBlock));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 150 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 151 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 152 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 153 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.LastPublished));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 154 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 155 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.UpdatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 156 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 157 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 158 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.NamespaceId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 159 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 160 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 161 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 162 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 162 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (Model.IsSite) {
    
            
            #line default
            #line hidden
            
            #line 163 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Title));

            
            #line default
            #line hidden
            
            #line 163 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 164 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
            
            #line 164 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 165 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
            
            #line 165 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 166 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
            
            #line 166 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                          
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 168 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!Piranha.Application.Current.IsMvc) {
    
            
            #line default
            #line hidden
            
            #line 169 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.PageView));

            
            #line default
            #line hidden
            
            #line 169 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                         
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 171 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Hidden("returl", (string)ViewBag.ReturnUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"draft\"");

WriteLiteral(" name=\"draft\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"org_parentid\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8271), Tuple.Create("\"", 8299)
            
            #line 173 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 8279), Tuple.Create<System.Object, System.Int32>(Model.Page.ParentId
            
            #line default
            #line hidden
, 8279), false)
);

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"first-row\"");

WriteLiteral(">\r\n    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 8346), Tuple.Create("\"", 8436)
            
            #line 176 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 8354), Tuple.Create<System.Object, System.Int32>(!String.IsNullOrEmpty(Model.Template.Preview.ToString()) ? "grid_9" : "grid_12"
            
            #line default
            #line hidden
, 8354), false)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 178 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                              Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n");

            
            #line 180 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 180 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                 if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                    <li>");

            
            #line 182 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 184 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 185 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n");

            
            #line 187 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
					
            
            #line default
            #line hidden
            
            #line 187 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                     if (!Model.Page.IsBlock) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<li>");

            
            #line 188 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t");

            
            #line 190 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                           Write(Html.TextBoxFor(m => m.Page.NavigationTitle, new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 191 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</li>\r\n");

            
            #line 193 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("                    <li");

WriteLiteral(" class=\"protected\"");

WriteLiteral(">");

            
            #line 194 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     Write(Html.LabelFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 195 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 195 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Permalink != null && !String.IsNullOrEmpty(Model.Permalink.Name)) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 196 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
            
            #line 196 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                               Write(Url.GetPermalink(Model.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 197 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p><i>");

            
            #line 198 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         Write(Piranha.Resources.Page.PermalinkDescription);

            
            #line default
            #line hidden
WriteLiteral("</i></p>\r\n");

            
            #line 199 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 201 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 202 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a");

WriteLiteral(" class=\"locked\"");

WriteLiteral("></a>\r\n                    </li>\r\n                    <li>\r\n                     " +
"   <label>");

            
            #line 206 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Piranha.Resources.Global.Placement);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <button");

WriteLiteral(" class=\"btn right\"");

WriteLiteral(" id=\"btnMove\"");

WriteLiteral(">");

            
            #line 207 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                          Write(Piranha.Resources.Global.Move);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 208 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 208 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (!Model.Page.IsStartpage) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 209 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.Resources.Global.PlacementPage);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");

            
            #line 209 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                       Write(Model.Page.Seqno > 1 ? @Piranha.Resources.Global.PlacementAfter : @Piranha.Resources.Global.PlacementBelow);

            
            #line default
            #line hidden
WriteLiteral("</strong> &quot;");

            
            #line 209 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                                                                                   Write(Model.PlaceRef);

            
            #line default
            #line hidden
WriteLiteral("&quot;</p>\r\n");

            
            #line 210 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 211 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.Resources.Global.PlacementStart);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 212 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"placement-edit\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 214 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" id=\"Page_ParentId\"");

WriteLiteral(" name=\"Page.ParentId\"");

WriteLiteral(">\r\n");

            
            #line 217 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 217 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     foreach (var p in Model.Parents) {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 10970), Tuple.Create("\"", 10983)
            
            #line 218 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 10978), Tuple.Create<System.Object, System.Int32>(p.Id
            
            #line default
            #line hidden
, 10978), false)
);

            
            #line 218 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                     Write(p.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 219 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.Raw(p.Title));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 220 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 223 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(" id=\"div-seqno\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" id=\"Page_Seqno\"");

WriteLiteral(" name=\"Page.Seqno\"");

WriteLiteral(">\r\n");

            
            #line 226 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 226 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 foreach (var s in Model.Siblings) {

            
            #line default
            #line hidden
WriteLiteral("                                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 11529), Tuple.Create("\"", 11545)
            
            #line 227 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 11537), Tuple.Create<System.Object, System.Int32>(s.Seqno
            
            #line default
            #line hidden
, 11537), false)
);

            
            #line 227 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                    Write(s.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 227 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                               Write(s.Title);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 228 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n  " +
"                      </div>\r\n                    </li>\r\n                </ul>\r\n" +
"");

            
            #line 234 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                } else {

            
            #line default
            #line hidden
WriteLiteral("                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 237 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.SiteTree.MetaTitle, Piranha.Resources.SiteTree.MetaTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 239 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.SiteTree.MetaTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 240 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 240 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (String.IsNullOrEmpty(Model.SiteTree.MetaTitle)) {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 241 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                      Write(Piranha.Resources.Page.KeywordsNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 242 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </li>\r\n                    <l" +
"i>\r\n");

WriteLiteral("                        ");

            
            #line 246 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.SiteTree.MetaDescription, Piranha.Resources.SiteTree.MetaDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 248 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextAreaFor(m => m.SiteTree.MetaDescription, new { @rows = 5 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 249 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 249 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (String.IsNullOrEmpty(Model.SiteTree.MetaDescription)) {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 250 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                      Write(Piranha.Resources.Page.DescriptionNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 251 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </li>\r\n                </ul>\r" +
"\n");

            
            #line 255 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 259 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 259 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!String.IsNullOrEmpty(Model.Template.Preview.ToString())) {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"grid_3\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box pagetemplate\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 262 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(!Model.IsSite ? Model.Template.Name : Model.SiteTree.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 13370), Tuple.Create("\"", 13419)
, Tuple.Create(Tuple.Create("", 13378), Tuple.Create("edit", 13378), true)
            
            #line 264 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 13382), Tuple.Create<System.Object, System.Int32>(Model.Page.IsBlock ? "block" : ""
            
            #line default
            #line hidden
, 13383), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 265 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 270 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div>\r\n    <div");

WriteLiteral(" class=\"grid_12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box main-content\"");

WriteLiteral(">\r\n            <table>\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"tools\"");

WriteLiteral(">\r\n                        <ul>\r\n                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 13773), Tuple.Create("\"", 13852)
, Tuple.Create(Tuple.Create("", 13781), Tuple.Create("btn-content", 13781), true)
            
            #line 279 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 13792), Tuple.Create<System.Object, System.Int32>(Model.Action != EditModel.ActionType.SEO ? "active" : ""
            
            #line default
            #line hidden
, 13793), false)
);

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-content\"");

WriteLiteral(">");

            
            #line 279 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                             Write(Piranha.Resources.Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 280 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 280 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (!Model.IsSite && !Model.Page.IsBlock) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 14037), Tuple.Create("\"", 14117)
, Tuple.Create(Tuple.Create("", 14045), Tuple.Create("btn-settings", 14045), true)
            
            #line 281 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 14057), Tuple.Create<System.Object, System.Int32>(Model.Action == EditModel.ActionType.SEO ? "active" : ""
            
            #line default
            #line hidden
, 14058), false)
);

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-settings\"");

WriteLiteral(">");

            
            #line 281 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                               Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 282 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 283 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (Model.Properties.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"btn-properties\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-properties\"");

WriteLiteral(">");

            
            #line 284 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                       Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 285 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 286 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"btn-comments\"");

WriteLiteral(">\r\n");

            
            #line 288 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 288 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  
                                    var count = Model.Comments.Where(c => c.Status == Piranha.Entities.Comment.CommentStatus.New).Count() ;
                                
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span ");

            
            #line 291 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  Write(count == 0 ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(" id=\"comment-notification\" class=\"notification\">");

            
            #line 291 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                          Write(count);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-comments\"");

WriteLiteral(">");

            
            #line 292 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                            </li>\r\n");

            
            #line 294 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 295 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             foreach (var ext in Model.Extensions) {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <a");

WriteLiteral(" href=\"#\"");

            
            #line 297 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(ExtensionManager.Current.GetIconPathByType(ext.Type) != "" ? "style=background-image:url('" + 
                                Url.Content(ExtensionManager.Current.GetIconPathByType(ext.Type)) + "')" : "");

            
            #line default
            #line hidden
WriteLiteral(" data-id=\"pnl-");

            
            #line 298 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                       Write(ExtensionManager.Current.GetInternalIdByType(ext.Type).ToLower());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");

WriteLiteral("                                    ");

            
            #line 299 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(ExtensionManager.Current.GetNameByType(ext.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </a>\r\n                            </li>\r\n");

            
            #line 302 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </td>\r\n                    <td" +
">\r\n                        <div");

WriteLiteral(" id=\"pnl-content\"");

WriteAttribute("class", Tuple.Create(" class=\"", 15862), Tuple.Create("\"", 15949)
, Tuple.Create(Tuple.Create("", 15870), Tuple.Create("main", 15870), true)
, Tuple.Create(Tuple.Create(" ", 15874), Tuple.Create("content-editor", 15875), true)
            
            #line 306 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 15889), Tuple.Create<System.Object, System.Int32>(Model.Action != EditModel.ActionType.SEO ? "" : "hidden"
            
            #line default
            #line hidden
, 15890), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" id=\"regionbuttons\"");

WriteLiteral(" class=\"buttons\"");

WriteLiteral(">\r\n");

            
            #line 309 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 309 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     for (int n = 0; n < Model.Regions.Count; n++) {

            
            #line default
            #line hidden
WriteLiteral("                                        <button");

WriteAttribute("id", Tuple.Create(" id=\"", 16209), Tuple.Create("\"", 16261)
            
            #line 310 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 16214), Tuple.Create<System.Object, System.Int32>(Html.Raw("btn_" + Model.Regions[n].InternalId)
            
            #line default
            #line hidden
, 16214), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 16262), Tuple.Create("\"", 16305)
, Tuple.Create(Tuple.Create("", 16270), Tuple.Create("btn", 16270), true)
            
            #line 310 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               , Tuple.Create(Tuple.Create("", 16273), Tuple.Create<System.Object, System.Int32>(n > 0 ? "" : " active"
            
            #line default
            #line hidden
, 16273), false)
, Tuple.Create(Tuple.Create(" ", 16298), Tuple.Create("region", 16299), true)
);

WriteLiteral(">");

            
            #line 310 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                            Write(Model.Regions[n].Name);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 311 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <button");

WriteLiteral(" id=\"btn_attachments\"");

WriteAttribute("class", Tuple.Create(" class=\"", 16443), Tuple.Create("\"", 16498)
, Tuple.Create(Tuple.Create("", 16451), Tuple.Create("btn", 16451), true)
            
            #line 312 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 16454), Tuple.Create<System.Object, System.Int32>(Model.Regions.Count == 0 ? " active" : ""
            
            #line default
            #line hidden
, 16454), false)
);

WriteLiteral(">");

            
            #line 312 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                    Write(Piranha.Resources.Page.Attachments);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </div>\r\n                              " +
"  <h2");

WriteLiteral(" id=\"section-title\"");

WriteLiteral(">");

            
            #line 314 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Piranha.Resources.Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n");

            
            #line 317 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 317 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 if (Model.Regions.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" id=\"regions\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 319 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Html.EditorFor(m => m.Regions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

            
            #line 321 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" id=\"attachments\"");

WriteLiteral(" ");

            
            #line 322 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Model.Regions.Count > 0 ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 323 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Html.Partial("Partial/Attachments"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n");

            
            #line 327 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 327 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-settings\"");

WriteAttribute("class", Tuple.Create(" class=\"", 17413), Tuple.Create("\"", 17485)
, Tuple.Create(Tuple.Create("", 17421), Tuple.Create("main", 17421), true)
            
            #line 328 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 17425), Tuple.Create<System.Object, System.Int32>(Model.Action == EditModel.ActionType.SEO ? "" : "hidden"
            
            #line default
            #line hidden
, 17426), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 329 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t<ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t<li>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 333 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 335 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.DropDownListFor(m => m.Page.GroupId, Model.Groups));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 337 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.DisabledGroups));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" id=\"disable-groups\"");

WriteLiteral(" class=\"block\"");

WriteLiteral(">\r\n");

            
            #line 339 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
											
            
            #line default
            #line hidden
            
            #line 339 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                               var dGroups = Model.Groups.Where(g => g.Value != Guid.Empty.ToString()).ToList(); 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 340 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.Partial("Partial/GroupList", new Piranha.Models.Manager.PageModels.GroupListModel() {
										   Groups = Model.DisableGroups, Page = Model.Page
									   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\t<li>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 346 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t<p>");

            
            #line 347 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      Write(Html.CheckBoxFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 347 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                               Write(Piranha.Resources.Page.HiddenDescription);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\t<li>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 350 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 352 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.Keywords, new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 353 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
											
            
            #line default
            #line hidden
            
            #line 353 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             if (Model.Action == EditModel.ActionType.SEO && String.IsNullOrEmpty(Model.Page.Keywords)) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 354 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Piranha.Resources.Page.KeywordsNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 355 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
											}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t\t</div>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 357 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\t<li>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 360 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 362 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextAreaFor(m => m.Page.Description, new { @rows = 3, @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 363 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
											
            
            #line default
            #line hidden
            
            #line 363 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             if (Model.Action == EditModel.ActionType.SEO && String.IsNullOrEmpty(Model.Page.Description)) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 364 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Piranha.Resources.Page.DescriptionNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 365 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
											}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t\t</div>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 367 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t</li>\r\n");

            
            #line 369 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
									
            
            #line default
            #line hidden
            
            #line 369 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowController) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t\t<li>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 371 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.LabelFor(m => m.Page.PageController,
											Piranha.Application.Current.IsMvc ? Piranha.Resources.Page.Route : Piranha.Resources.Page.Template));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 374 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageController, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Controller) ? Model.Template.Controller : "Page" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 376 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageController));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t</li>\r\n");

            
            #line 378 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
									}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 379 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Piranha.Application.Current.IsMvc && Model.Template.ShowView) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t\t<li>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 381 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.LabelFor(m => m.Page.PageView));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 383 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageView, new { @placeholder = !String.IsNullOrEmpty(Model.Template.View) ? Model.Template.View : "Index" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 385 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageView));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t</li>\r\n");

            
            #line 387 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
									}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 388 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowRedirect) {

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t\t\t<li>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 390 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.LabelFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t<div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t\t");

            
            #line 392 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageRedirect, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Redirect) ? Model.Template.Redirect : Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t\t");

            
            #line 394 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t\t</li>\r\n");

            
            #line 396 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
									}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t</ul>\r\n\r\n                            </div>\r\n                        </di" +
"v>\r\n");

            
            #line 401 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 402 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Properties.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-properties\"");

WriteLiteral(" class=\"main hidden\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 404 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n");

            
            #line 407 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 407 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 for (int n = 0; n < Model.Properties.Count; n++) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 408 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Properties[n], Model.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 409 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 410 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 411 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 412 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 413 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 414 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 415 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 417 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Properties[n].Value));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </li>\r\n");

            
            #line 419 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");

            
            #line 423 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 424 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-comments\"");

WriteLiteral(" class=\"main content-editor hidden\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 426 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner region-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 428 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                           Write(Html.Partial("~/Areas/Manager/Views/Comment/List.cshtml", Model.Comments));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 431 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 432 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"grid_3 hidden\"");

WriteLiteral(">\r\n");

            
            #line 440 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 440 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!Model.Page.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"box expandable\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 442 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Piranha.Resources.Global.Versioning);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div");

WriteLiteral(" class=\"inner optional\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n                <li>");

            
            #line 445 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.LastPublished);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 446 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                Write(Model.Page.LastPublished > DateTime.MinValue ? Model.Page.LastPublished.ToShortDateString() : "");

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");

            
            #line 447 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Published);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 448 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                Write(Model.Page.Published > DateTime.MinValue ? Model.Page.Published.ToShortDateString() : "");

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");

            
            #line 449 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">");

            
            #line 449 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Model.Page.Updated.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");

            
            #line 450 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">");

            
            #line 450 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Model.Page.Created.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n");

            
            #line 454 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 456 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Foot", () => {

WriteLiteral("\r\n <div");

WriteLiteral(" id=\"boxContent\"");

WriteLiteral(" class=\"floatbox\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bg\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(" style=\"min-width: 510px;min-height:260px;\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n");

});

        }
    }
}
#pragma warning restore 1591
