#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Settings
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Settings/Param.cshtml")]
    public partial class Param : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.SettingModels.ParamEditModel>
    {
        public Param()
        {
        }
        public override void Execute()
        {
DefineSection("Toolbar", () => {

WriteLiteral("\r\n");

            
            #line 3 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n        <ul>\r\n            <li><a");

WriteLiteral(" class=\"save submit\"");

WriteLiteral(">");

            
            #line 7 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 8 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
            
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
             if (!Model.Param.IsLocked) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 321), Tuple.Create("\"", 383)
            
            #line 9 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
, Tuple.Create(Tuple.Create("", 328), Tuple.Create<System.Object, System.Int32>(Url.Action("deleteparam", new { id = Model.Param.Id })
            
            #line default
            #line hidden
, 328), false)
);

WriteLiteral(" class=\"delete\"");

WriteLiteral(">");

            
            #line 9 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                            Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 10 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 483), Tuple.Create("\"", 514)
            
            #line 11 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
, Tuple.Create(Tuple.Create("", 490), Tuple.Create<System.Object, System.Int32>(Url.Action("paramlist")
            
            #line default
            #line hidden
, 490), false)
);

WriteLiteral(" class=\"back\"");

WriteLiteral(">");

            
            #line 11 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                           Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 595), Tuple.Create("\"", 651)
            
            #line 12 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
, Tuple.Create(Tuple.Create("", 602), Tuple.Create<System.Object, System.Int32>(Url.Action("param", new { id = Model.Param.Id })
            
            #line default
            #line hidden
, 602), false)
);

WriteLiteral(" class=\"refresh\"");

WriteLiteral(">");

            
            #line 12 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                       Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n");

});

            
            #line 18 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
   Html.BeginForm() ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 19 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.HiddenFor(m => m.Param.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 20 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.HiddenFor(m => m.Param.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 21 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.HiddenFor(m => m.Param.IsLocked));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 22 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.HiddenFor(m => m.Param.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 23 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.HiddenFor(m => m.Param.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"grid_12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>Information</h2></div>\r\n        <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 30 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
               Write(Html.LabelFor(m => m.Param.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                         if (!Model.Param.IsLocked) {
                            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextBoxFor(m => m.Param.Name));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                               
                        } else {
                            
            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextBoxFor(m => m.Param.Name, new { @disabled = "disabled" }));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                               
                            
            
            #line default
            #line hidden
            
            #line 36 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.HiddenFor(m => m.Param.Name));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                              
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
               Write(Html.ValidationMessageFor(m => m.Param.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 42 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
               Write(Html.LabelFor(m => m.Param.Value));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

            
            #line 44 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                         if (Model.Param.Name != "SITE_VERSION") {
                            
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextBoxFor(m => m.Param.Value));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                
                        } else {
                            
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextBoxFor(m => m.Param.Value, new { @disabled = "disabled" }));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                                
                            
            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.HiddenFor(m => m.Param.Value));

            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                               
                        } 

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </li>\r\n                <li>\r\n");

WriteLiteral("                    ");

            
            #line 53 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
               Write(Html.LabelFor(m => m.Param.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

            
            #line 55 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                         if (!Model.Param.IsLocked) {
                            
            
            #line default
            #line hidden
            
            #line 56 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextAreaFor(m => m.Param.Description, 
                                new { @rows = 3, @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                                    
                        } else {
                            
            
            #line default
            #line hidden
            
            #line 59 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextAreaFor(m => m.Param.Description, 
                                new { @rows = 3, @disabled = "disabled", @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
            
            #line 60 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                                                            
                            
            
            #line default
            #line hidden
            
            #line 61 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.HiddenFor(m => m.Param.Description));

            
            #line default
            #line hidden
            
            #line 61 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                     
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </li>\r\n            </ul>\r\n        </d" +
"iv>\r\n    </div>\r\n</div>\r\n");

            
            #line 69 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
