#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Extensions.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Extensions/EditorTemplates/Attachment.cshtml")]
    public partial class _Attachment : System.Web.Mvc.WebViewPage<Piranha.Extend.Regions.AttachmentRegion.Attachment>
    {
        public _Attachment()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
  
    Layout = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n<tr>\r\n    <td>\r\n");

WriteLiteral("        ");

            
            #line 7 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.LastPublished));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 10 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 312), Tuple.Create("\"", 358)
            
            #line 12 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
, Tuple.Create(Tuple.Create("", 318), Tuple.Create<System.Object, System.Int32>(Url.GetThumbnailUrl((Guid)Model.Id, 50)
            
            #line default
            #line hidden
, 318), false)
);

WriteLiteral(" /></td>\r\n    <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 379), Tuple.Create("\"", 478)
            
            #line 13 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
, Tuple.Create(Tuple.Create("", 386), Tuple.Create<System.Object, System.Int32>(Url.Action("edit", "content", new { @id = Model.Id, @returl = Url.Action("edit", "page") })
            
            #line default
            #line hidden
, 386), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"list-info\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
       Write(Html.Raw(Model.LastPublished == DateTime.MinValue ? "<span class=info-unpublished></span>" : 
                (Model.Updated > Model.LastPublished ? "<span class=info-draft></span>" : "")));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </a></td>\r\n    <td>");

            
            #line 20 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Model.Type);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    <td");

WriteLiteral(" class=\"buttons three\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"icon up marg\"");

WriteLiteral("></a>\r\n        <a");

WriteLiteral(" class=\"icon down marg\"");

WriteLiteral("></a>\r\n        <a");

WriteLiteral(" class=\"icon delete\"");

WriteLiteral("></a></td>\r\n</tr>\r\n");

        }
    }
}
#pragma warning restore 1591
