#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Page
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
    using Piranha.Extend;
    
    #line default
    #line hidden
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/EditCopy.cshtml")]
    public partial class EditCopy : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.PageModels.EditModel>
    {
        public EditCopy()
        {
        }
        public override void Execute()
        {
DefineSection("Head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 127), Tuple.Create("\"", 189)
, Tuple.Create(Tuple.Create("", 133), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.form.js")
, 133), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 236), Tuple.Create("\"", 301)
, Tuple.Create(Tuple.Create("", 242), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.regions.js")
, 242), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 348), Tuple.Create("\"", 416)
, Tuple.Create(Tuple.Create("", 354), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.attachment.js")
, 354), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 463), Tuple.Create("\"", 533)
, Tuple.Create(Tuple.Create("", 469), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.media.dialog.js")
, 469), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 580), Tuple.Create("\"", 646)
, Tuple.Create(Tuple.Create("", 586), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.comments.js")
, 586), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 693), Tuple.Create("\"", 767)
, Tuple.Create(Tuple.Create("", 699), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/ext/jquery.equalheights.js")
, 699), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var folderId = """";

        $(document).ready(function () {
            $(""#Page_Title"").focus();

            $(""#Page_ParentId"").change(function () {
                var page_id = $(""#Page_Id"").val();
                var page_parentid = $(""#org_parentid"").val();
                var page_seqno = $(""#Page_Seqno"").val();
                var parentid = $(""#Page_ParentId"").val();
                var site_tree = $(""#Page_SiteTreeInternalId"").val();

                $.get(""");

            
            #line 23 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                  Write(Url.Action("siblings"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&page_parentid="" + page_parentid + ""&page_seqno="" + page_seqno + ""&parentid="" + parentid + ""&site_tree="" + site_tree, function (data) {
                    $(""#div-seqno"").html(data);
                });
            });

            $('#Page_GroupId').change(function() {
                var page_id = $(""#Page_Id"").val();
                var group_id = $(this).val();

                $.get(""");

            
            #line 32 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                  Write(Url.Action("grouplist"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&group_id="" + group_id, function(data) {
                    $(""#disable-groups"").html(data);
                });
            });

            $('#btnMove').click(function () {
                $('#placement-edit').slideToggle('fast');
                $(this).toggleClass('active');
                return false;
            });

            $('.first-row .box').equalHeights();

            var c = new piranha.comment('");

            
            #line 45 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                    Write(Model.Page.Id);

            
            #line default
            #line hidden
WriteLiteral("\', \'comment-notification\', \'pnl-comments .inner\');\r\n        });\r\n\r\n        //\r\n  " +
"      // Hides all editors on the page. This callback is called from jquery.atta" +
"chments.js\r\n        //\r\n        function hideEditors() {\r\n            $(\"#pagere" +
"gions .input, #globalregions .input\").hide();\r\n            $(\"#regionbuttons but" +
"ton\").removeClass(\"active\");\r\n            $(\"#attachments\").hide();\r\n\r\n         " +
"   $(\"#regions .region-body\").hide();\r\n            $(\"#regionbuttons button\").re" +
"moveClass(\"active\");\r\n            $(\"#attachments\").hide();\r\n        }\r\n\r\n      " +
"  //\r\n        // This callback is called from jquery.attachments.js\r\n        //\r" +
"\n        function addAttachment(a) {\r\n            // Store folder id so we can o" +
"pen the same folder next time.\r\n            folderId = a.ParentId;\r\n\r\n          " +
"  // Add the attachment\r\n            $(\".attachments\").append(\r\n                " +
"\'<tr data-id=\"\' + a.Id + \'\">\' +\r\n                    \'<td><img src=\"\' + a.Thumbn" +
"ailUrl + \'/50\")\" /></td>\' +\r\n                    \'<td>\' + a.DisplayName + \'</td>" +
"\' +\r\n                    \'<td>\' + a.Type + \'</td>\' +\r\n                    \'<td c" +
"lass=\"buttons three\">\' +\r\n                        \'<a class=\"icon up marg\"></a>\'" +
" +\r\n                        \'<a class=\"icon down marg\"></a>\' +\r\n                " +
"        \'<a class=\"icon delete\"></a></td>\' +\r\n                \'</tr>\') ;\r\n      " +
"  }\r\n\r\n        //\r\n        // This callback is called from jquery.attachments.js" +
" before form submit.\r\n        //\r\n        function addAttachmentData(index, val)" +
" {\r\n            $(\"#attachment_data\").append(\r\n                    \'<input id=\"P" +
"age_Attachments_\' + index +\r\n                    \'_\" name=\"Page.Attachments[\' + " +
"index +\r\n                    \']\" type=\"hidden\" value=\"\' + $(val).attr(\"data-id\")" +
" + \'\" />\');\r\n        }\r\n    </script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Toolbar", () => {

WriteLiteral("\r\n");

            
            #line 94 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n        <ul>\r\n            <li><a");

WriteLiteral(" class=\"save submit\"");

WriteLiteral(">");

            
            #line 98 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 99 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
            
            
            #line default
            #line hidden
            
            #line 99 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
             if (!Model.Page.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4316), Tuple.Create("\"", 4469)
, Tuple.Create(Tuple.Create("", 4323), Tuple.Create("http://", 4323), true)
            
            #line 100 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 4330), Tuple.Create<System.Object, System.Int32>(Request.Url.DnsSafeHost
            
            #line default
            #line hidden
, 4330), false)
            
            #line 100 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 4354), Tuple.Create<System.Object, System.Int32>(!Request.Url.IsDefaultPort ? ":" + Request.Url.Port.ToString() : ""
            
            #line default
            #line hidden
, 4354), false)
            
            #line 100 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                              , Tuple.Create(Tuple.Create("", 4424), Tuple.Create<System.Object, System.Int32>(Url.GetPermalink(Model.Page.Permalink, true)
            
            #line default
            #line hidden
, 4424), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(" class=\"preview\"");

WriteLiteral(">");

            
            #line 100 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                                                                                                                                         Write(Piranha.Resources.Global.ToolbarPreview);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 101 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 102 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
             if (Model.CanPublish && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteLiteral(" class=\"publish\"");

WriteLiteral(">");

            
            #line 103 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                              Write(Piranha.Resources.Global.ToolbarPublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 104 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 105 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
             if (Model.Page.Published > DateTime.MinValue && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4869), Tuple.Create("\"", 4928)
            
            #line 106 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 4876), Tuple.Create<System.Object, System.Int32>(Url.Action("unpublish", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 4876), false)
);

WriteLiteral(" class=\"unpublish\"");

WriteLiteral(">");

            
            #line 106 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                            Write(Piranha.Resources.Global.ToolbarUnpublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 107 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 108 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
             if (Model.Page.Published > DateTime.MinValue && Model.Page.Updated > Model.Page.LastPublished) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5145), Tuple.Create("\"", 5201)
            
            #line 109 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 5152), Tuple.Create<System.Object, System.Int32>(Url.Action("revert", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5152), false)
);

WriteLiteral(" class=\"revert\"");

WriteLiteral(">");

            
            #line 109 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarRevert);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 110 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 111 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
             if (!Model.Page.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5340), Tuple.Create("\"", 5396)
            
            #line 112 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 5347), Tuple.Create<System.Object, System.Int32>(Url.Action("detach", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5347), false)
);

WriteLiteral(" class=\"detach\"");

WriteLiteral(">Detach</a></li>\r\n");

            
            #line 113 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 114 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
             if (!Model.Page.IsNew && Model.CanDelete && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5561), Tuple.Create("\"", 5617)
            
            #line 115 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 5568), Tuple.Create<System.Object, System.Int32>(Url.Action("delete", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5568), false)
);

WriteLiteral(" class=\"delete\"");

WriteLiteral(">");

            
            #line 115 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 116 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5717), Tuple.Create("\"", 5772)
            
            #line 117 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 5724), Tuple.Create<System.Object, System.Int32>(Url.Action("index", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5724), false)
);

WriteLiteral(" class=\"back\"");

WriteLiteral(">");

            
            #line 117 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                   Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5853), Tuple.Create("\"", 5907)
            
            #line 118 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 5860), Tuple.Create<System.Object, System.Int32>(Url.Action("edit", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5860), false)
);

WriteLiteral(" class=\"refresh\"");

WriteLiteral(">");

            
            #line 118 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                     Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

WriteLiteral("            ");

            
            #line 119 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
       Write(Piranha.WebPages.Hooks.Manager.Toolbar.Render(Url, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n");

});

WriteLiteral("<div>\r\n    <div");

WriteLiteral(" class=\"grid_12 page-message\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box info\"");

WriteLiteral(" style=\"margin:0 0 30px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ico\"");

WriteLiteral("></div>\r\n                <p>This page is a copy. To edit the actual content of th" +
"e page, please edit the original <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6405), Tuple.Create("\"", 6493)
            
            #line 130 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                  , Tuple.Create(Tuple.Create("", 6412), Tuple.Create<System.Object, System.Int32>(Url.Action("edit", new { @id = Model.Page.OriginalId, @returl = Model.Page.Id })
            
            #line default
            #line hidden
, 6412), false)
);

WriteLiteral(">here</a>.</p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

            
            #line 135 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
   Html.BeginForm("edit", (string)ViewContext.RouteData.Values["Controller"]) ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 137 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 138 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 139 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeInternalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 140 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.OriginalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 141 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 142 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 143 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 144 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.TemplateId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 145 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.PermalinkId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 146 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 147 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 148 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 149 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 150 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.LastPublished));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 151 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 152 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Page.UpdatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 153 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Permalink.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 154 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 155 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Permalink.NamespaceId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 156 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 157 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 158 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
Write(Html.HiddenFor(m => m.Permalink.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"draft\"");

WriteLiteral(" name=\"draft\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"org_parentid\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7747), Tuple.Create("\"", 7775)
            
            #line 160 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 7755), Tuple.Create<System.Object, System.Int32>(Model.Page.ParentId
            
            #line default
            #line hidden
, 7755), false)
);

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"first-row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"grid_9\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 165 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                              Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                    <li>");

            
            #line 168 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                   Write(Html.LabelFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 170 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 171 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li>");

            
            #line 173 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                   Write(Html.LabelFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 175 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.NavigationTitle, new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 176 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"protected\"");

WriteLiteral(">");

            
            #line 178 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                     Write(Html.LabelFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 179 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 179 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                         if (Model.Permalink != null && !String.IsNullOrEmpty(Model.Permalink.Name)) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>http://");

            
            #line 180 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                             Write(Request.Url.DnsSafeHost);

            
            #line default
            #line hidden
            
            #line 180 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                     Write(Url.GetPermalink(Model.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 181 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p><i>");

            
            #line 182 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                         Write(Piranha.Resources.Page.PermalinkDescription);

            
            #line default
            #line hidden
WriteLiteral("</i></p>\r\n");

            
            #line 183 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 185 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                       Write(Html.TextBoxFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 186 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a");

WriteLiteral(" class=\"locked\"");

WriteLiteral("></a>\r\n                    </li>\r\n                    <li>\r\n                     " +
"   <label>");

            
            #line 190 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                          Write(Piranha.Resources.Global.Placement);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <button");

WriteLiteral(" class=\"btn right\"");

WriteLiteral(" id=\"btnMove\"");

WriteLiteral(">Move</button>\r\n");

            
            #line 192 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 192 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                         if (!Model.Page.IsStartpage) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 193 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                      Write(Piranha.Resources.Global.PlacementPage);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");

            
            #line 193 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                       Write(Model.Page.Seqno > 1 ? @Piranha.Resources.Global.PlacementAfter : @Piranha.Resources.Global.PlacementBelow);

            
            #line default
            #line hidden
WriteLiteral("</strong> &quot;");

            
            #line 193 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                                                                                                                                   Write(Model.PlaceRef);

            
            #line default
            #line hidden
WriteLiteral("&quot;</p>\r\n");

            
            #line 194 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 195 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                      Write(Piranha.Resources.Global.PlacementStart);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 196 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"placement-edit\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 198 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                       Write(Html.LabelFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" id=\"Page_ParentId\"");

WriteLiteral(" name=\"Page.ParentId\"");

WriteLiteral(">\r\n");

            
            #line 201 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 201 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                     foreach (var p in Model.Parents) {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 10335), Tuple.Create("\"", 10348)
            
            #line 202 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 10343), Tuple.Create<System.Object, System.Int32>(p.Id
            
            #line default
            #line hidden
, 10343), false)
);

            
            #line 202 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                     Write(p.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 203 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                   Write(Html.Raw(p.Title));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 204 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 207 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                       Write(Html.LabelFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(" id=\"div-seqno\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" id=\"Page_Seqno\"");

WriteLiteral(" name=\"Page.Seqno\"");

WriteLiteral(">\r\n");

            
            #line 210 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 210 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                 foreach (var s in Model.Siblings) {

            
            #line default
            #line hidden
WriteLiteral("                                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 10894), Tuple.Create("\"", 10910)
            
            #line 211 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
, Tuple.Create(Tuple.Create("", 10902), Tuple.Create<System.Object, System.Int32>(s.Seqno
            
            #line default
            #line hidden
, 10902), false)
);

            
            #line 211 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                    Write(s.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 211 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                               Write(s.Title);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 212 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n  " +
"                      </div>\r\n                    </li>\r\n                </ul>\r\n" +
"            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"grid_3\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box pagetemplate\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 223 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                              Write(Model.Template.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"edit\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 226 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
               Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r" +
"\n<div>\r\n    <div");

WriteLiteral(" class=\"grid_12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box main-content\"");

WriteLiteral(">\r\n            <table>\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"tools\"");

WriteLiteral(">\r\n                        <ul>\r\n                            <li");

WriteLiteral(" class=\"btn-settings active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-settings\"");

WriteLiteral(">");

            
            #line 239 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                          Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 240 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 240 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                             if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"btn-comments\"");

WriteLiteral(">\r\n");

            
            #line 242 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 242 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                  
                                    var count = Model.Comments.Where(c => c.Status == Piranha.Entities.Comment.CommentStatus.New).Count() ;
                                
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span ");

            
            #line 245 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                  Write(count == 0 ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(" id=\"comment-notification\" class=\"notification\">");

            
            #line 245 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                                                          Write(count);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-comments\"");

WriteLiteral(">");

            
            #line 246 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                            </li>\r\n");

            
            #line 248 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 249 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                             foreach (var ext in Model.Extensions) {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <a");

WriteLiteral(" href=\"#\"");

            
            #line 251 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                       Write(ExtensionManager.GetIconPathByType(ext.Type) != "" ? "style=background-image:url('" + 
                                Url.Content(ExtensionManager.GetIconPathByType(ext.Type)) + "')" : "");

            
            #line default
            #line hidden
WriteLiteral(" data-id=\"pnl-");

            
            #line 252 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                                                               Write(ExtensionManager.GetInternalIdByType(ext.Type).ToLower());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");

WriteLiteral("                                    ");

            
            #line 253 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                               Write(ExtensionManager.GetExtensionNameByType(ext.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </a>\r\n                            </li>\r\n");

            
            #line 256 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </td>\r\n                    <td" +
">\r\n                        <div");

WriteLiteral(" id=\"pnl-settings\"");

WriteLiteral(" class=\"main\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 261 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                              Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                                    <li>\r\n");

WriteLiteral("                                        ");

            
            #line 265 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                   Write(Html.LabelFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <p>");

            
            #line 266 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                      Write(Html.CheckBoxFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 266 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                                                               Write(Piranha.Resources.Page.HiddenDescription);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                                    </li>\r\n                               " +
"     <li>");

            
            #line 268 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 270 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageController, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Controller) ? Model.Template.Controller : Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                                        ");

            
            #line 271 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");

            
            #line 273 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 273 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                     if (Model.Template.ShowRedirect) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 274 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 276 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageRedirect, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Redirect) ? Model.Template.Redirect : Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                                        ");

            
            #line 277 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");

            
            #line 279 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");

            
            #line 283 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 283 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                         if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-comments\"");

WriteLiteral(" class=\"main content-editor hidden\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 285 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner region-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 287 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                           Write(Html.Partial("~/Areas/Manager/Views/Comment/List.cshtml", Model.Comments));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 290 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 291 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
                   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n");

            
            #line 298 "..\..\Areas\Manager\Views\Page\EditCopy.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
