#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Page
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Extend;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Models.Manager.PageModels;
    
    #line default
    #line hidden
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.PageModels.EditModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {
DefineSection("Head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 170), Tuple.Create("\"", 232)
, Tuple.Create(Tuple.Create("", 176), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.form.js")
, 176), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 279), Tuple.Create("\"", 344)
, Tuple.Create(Tuple.Create("", 285), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.regions.js")
, 285), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 391), Tuple.Create("\"", 459)
, Tuple.Create(Tuple.Create("", 397), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.attachment.js")
, 397), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 506), Tuple.Create("\"", 576)
, Tuple.Create(Tuple.Create("", 512), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.media.dialog.js")
, 512), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 623), Tuple.Create("\"", 689)
, Tuple.Create(Tuple.Create("", 629), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/jquery.comments.js")
, 629), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 736), Tuple.Create("\"", 810)
, Tuple.Create(Tuple.Create("", 742), Tuple.Create<System.Object, System.Int32>(Href("~/r.ashx/piranha/areas/manager/content/js/ext/jquery.equalheights.js")
, 742), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("~/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var folderId = \"\";\r\n\r\n        $(document).ready(function () {\r\n       " +
"     // UI Stuff\r\n            $(\"#Page_Title\").focus();\r\n            $(\'.first-r" +
"ow .box\').equalHeights();\r\n\r\n");

            
            #line 20 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Action == EditModel.ActionType.ATTACHMENTS) {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n            $(\'#btn_attachments\').click();\r\n            ");

WriteLiteral("\r\n");

            
            #line 24 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"
            $(""#Page_ParentId"").change(function () {
                var page_id = $(""#Page_Id"").val();
                var page_parentid = $(""#org_parentid"").val();
                var page_seqno = $(""#Page_Seqno"").val();
                var parentid = $(""#Page_ParentId"").val();
                var site_tree = $(""#Page_SiteTreeInternalId"").val();

                $.get(""");

            
            #line 33 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("siblings"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&page_parentid="" + page_parentid + ""&page_seqno="" + page_seqno + ""&parentid="" + parentid + ""&site_tree="" + site_tree, function (data) {
                    $(""#div-seqno"").html(data);
                });
            });

            $('#Page_GroupId').change(function() {
                var page_id = $(""#Page_Id"").val();
                var group_id = $(this).val();

                $.get(""");

            
            #line 42 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("grouplist"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&group_id="" + group_id, function(data) {
                    $(""#disable-groups"").html(data);
                });
            });

            $('#btnMove').click(function () {
                $('#placement-edit').slideToggle('fast');
                $(this).toggleClass('active');
                return false;
            });

            new piranha.comment('");

            
            #line 53 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            Write(Model.Page.Id);

            
            #line default
            #line hidden
WriteLiteral("\', \'comment-notification\', \'pnl-comments .inner\');\r\n            \r\n            new" +
" piranha.media(\'btn_attach\', \'boxContent\', function (a) {\r\n                // St" +
"ore folder id so we can open the same folder next time.\r\n                folderI" +
"d = a.ParentId;\r\n\r\n                // Add the attachment\r\n                $(\".at" +
"tachments\").append(\r\n                    \'<tr data-id=\"\' + a.Id + \'\">\' +\r\n      " +
"                  \'<td><img src=\"\' + a.ThumbnailUrl + \'/50\" /></td>\' +\r\n        " +
"                \'<td>\' + a.DisplayName + \'</td>\' +\r\n                        \'<td" +
">\' + a.Type + \'</td>\' +\r\n                        \'<td class=\"buttons three\">\' +\r" +
"\n                            \'<a class=\"icon up marg\"></a>\' +\r\n                 " +
"           \'<a class=\"icon down marg\"></a>\' +\r\n                            \'<a c" +
"lass=\"icon delete\"></a></td>\' +\r\n                    \'</tr>\');\r\n            });\r" +
"\n        });\r\n\r\n        //\r\n        // Hides all editors on the page. This callb" +
"ack is called from jquery.attachments.js\r\n        //\r\n        function hideEdito" +
"rs() {\r\n            $(\"#pageregions .input, #globalregions .input\").hide();\r\n   " +
"         $(\"#regionbuttons button\").removeClass(\"active\");\r\n            $(\"#atta" +
"chments\").hide();\r\n\r\n            $(\"#regions .region-body\").hide();\r\n           " +
" $(\"#regionbuttons button\").removeClass(\"active\");\r\n            $(\"#attachments\"" +
").hide();\r\n        }\r\n\r\n        //\r\n        // This callback is called from jque" +
"ry.attachments.js before form submit.\r\n        //\r\n        function addAttachmen" +
"tData(index, val) {\r\n            $(\"#attachment_data\").append(\r\n                " +
"    \'<input id=\"Page_Attachments_\' + index +\r\n                    \'_\" name=\"Page" +
".Attachments[\' + index +\r\n                    \']\" type=\"hidden\" value=\"\' + $(val" +
").attr(\"data-id\") + \'\" />\');\r\n        }\r\n    </script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Toolbar", () => {

WriteLiteral("\r\n");

            
            #line 99 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n        <ul>\r\n            <li><a");

WriteLiteral(" class=\"save submit\"");

WriteLiteral(">");

            
            #line 103 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 104 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            
            
            #line default
            #line hidden
            
            #line 104 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (!Model.Page.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4637), Tuple.Create("\"", 4730)
            
            #line 105 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4644), Tuple.Create<System.Object, System.Int32>(Piranha.WebPages.WebPiranha.GetSiteUrl()
            
            #line default
            #line hidden
, 4644), false)
            
            #line 105 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4685), Tuple.Create<System.Object, System.Int32>(Url.GetPermalink(Model.Page.Permalink, true)
            
            #line default
            #line hidden
, 4685), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(" class=\"preview\"");

WriteLiteral(">");

            
            #line 105 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                             Write(Piranha.Resources.Global.ToolbarPreview);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 106 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 107 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteLiteral(" class=\"publish\"");

WriteLiteral(">");

            
            #line 108 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                              Write(Piranha.Resources.Global.ToolbarPublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 109 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 110 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Page.Published > DateTime.MinValue && !Model.IsSite && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5127), Tuple.Create("\"", 5186)
            
            #line 111 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5134), Tuple.Create<System.Object, System.Int32>(Url.Action("unpublish", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5134), false)
);

WriteLiteral(" class=\"unpublish\"");

WriteLiteral(">");

            
            #line 111 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                            Write(Piranha.Resources.Global.ToolbarUnpublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 112 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 113 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Page.Published > DateTime.MinValue && Model.Page.Updated > Model.Page.LastPublished) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5403), Tuple.Create("\"", 5459)
            
            #line 114 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5410), Tuple.Create<System.Object, System.Int32>(Url.Action("revert", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5410), false)
);

WriteLiteral(" class=\"revert\"");

WriteLiteral(">");

            
            #line 114 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarRevert);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 115 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 116 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (!Model.Page.IsNew && Model.CanDelete && !Model.IsSite && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5674), Tuple.Create("\"", 5730)
            
            #line 117 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5681), Tuple.Create<System.Object, System.Int32>(Url.Action("delete", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5681), false)
);

WriteLiteral(" class=\"delete\"");

WriteLiteral(">");

            
            #line 117 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 118 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 119 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (String.IsNullOrEmpty(ViewBag.ReturnUrl)) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5891), Tuple.Create("\"", 5946)
            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5898), Tuple.Create<System.Object, System.Int32>(Url.Action("index", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5898), false)
);

WriteLiteral(" class=\"back\"");

WriteLiteral(">");

            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                   Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 121 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6049), Tuple.Create("\"", 6074)
            
            #line 122 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6056), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnUrl
            
            #line default
            #line hidden
, 6056), false)
);

WriteLiteral(" class=\"back\"");

WriteLiteral(">");

            
            #line 122 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                     Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 123 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6170), Tuple.Create("\"", 6224)
            
            #line 124 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6177), Tuple.Create<System.Object, System.Int32>(Url.Action("edit", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 6177), false)
);

WriteLiteral(" class=\"refresh\"");

WriteLiteral(">");

            
            #line 124 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                     Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

WriteLiteral("            ");

            
            #line 125 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
       Write(Piranha.WebPages.Hooks.Manager.Toolbar.Render(Url, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n");

});

WriteLiteral("\r\n");

            
            #line 132 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.BeginForm("edit", (string)ViewContext.RouteData.Values["Controller"]) ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 134 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 135 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 136 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeInternalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 137 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.OriginalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 138 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 139 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 140 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 141 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.TemplateId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 142 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.PermalinkId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 143 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 144 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 145 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 146 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 147 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.LastPublished));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 148 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 149 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.UpdatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 150 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 151 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 152 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.NamespaceId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 153 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 154 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 155 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 156 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 156 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (Model.IsSite) {
    
            
            #line default
            #line hidden
            
            #line 157 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Title));

            
            #line default
            #line hidden
            
            #line 157 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 158 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
            
            #line 158 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 159 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
            
            #line 159 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 160 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
            
            #line 160 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                          
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 162 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Hidden("returl", (string)ViewBag.ReturnUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"draft\"");

WriteLiteral(" name=\"draft\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"org_parentid\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7875), Tuple.Create("\"", 7903)
            
            #line 164 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 7883), Tuple.Create<System.Object, System.Int32>(Model.Page.ParentId
            
            #line default
            #line hidden
, 7883), false)
);

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"first-row\"");

WriteLiteral(">\r\n    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 7950), Tuple.Create("\"", 8040)
            
            #line 167 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 7958), Tuple.Create<System.Object, System.Int32>(!String.IsNullOrEmpty(Model.Template.Preview.ToString()) ? "grid_9" : "grid_12"
            
            #line default
            #line hidden
, 7958), false)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 169 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                              Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n");

            
            #line 171 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 171 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                 if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                    <li>");

            
            #line 173 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 175 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 176 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li>");

            
            #line 178 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 180 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.NavigationTitle, new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 181 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"protected\"");

WriteLiteral(">");

            
            #line 183 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     Write(Html.LabelFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 184 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 184 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Permalink != null && !String.IsNullOrEmpty(Model.Permalink.Name)) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 185 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
            
            #line 185 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                               Write(Url.GetPermalink(Model.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 186 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p><i>");

            
            #line 187 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         Write(Piranha.Resources.Page.PermalinkDescription);

            
            #line default
            #line hidden
WriteLiteral("</i></p>\r\n");

            
            #line 188 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 190 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 191 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a");

WriteLiteral(" class=\"locked\"");

WriteLiteral("></a>\r\n                    </li>\r\n                    <li>\r\n                     " +
"   <label>");

            
            #line 195 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Piranha.Resources.Global.Placement);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <button");

WriteLiteral(" class=\"btn right\"");

WriteLiteral(" id=\"btnMove\"");

WriteLiteral(">Move</button>\r\n");

            
            #line 197 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 197 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (!Model.Page.IsStartpage) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 198 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.Resources.Global.PlacementPage);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");

            
            #line 198 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                       Write(Model.Page.Seqno > 1 ? @Piranha.Resources.Global.PlacementAfter : @Piranha.Resources.Global.PlacementBelow);

            
            #line default
            #line hidden
WriteLiteral("</strong> &quot;");

            
            #line 198 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                                                                                   Write(Model.PlaceRef);

            
            #line default
            #line hidden
WriteLiteral("&quot;</p>\r\n");

            
            #line 199 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 200 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.Resources.Global.PlacementStart);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 201 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"placement-edit\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 203 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" id=\"Page_ParentId\"");

WriteLiteral(" name=\"Page.ParentId\"");

WriteLiteral(">\r\n");

            
            #line 206 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 206 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     foreach (var p in Model.Parents) {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 10588), Tuple.Create("\"", 10601)
            
            #line 207 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 10596), Tuple.Create<System.Object, System.Int32>(p.Id
            
            #line default
            #line hidden
, 10596), false)
);

            
            #line 207 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                     Write(p.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 208 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.Raw(p.Title));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 209 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 212 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(" id=\"div-seqno\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" id=\"Page_Seqno\"");

WriteLiteral(" name=\"Page.Seqno\"");

WriteLiteral(">\r\n");

            
            #line 215 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 215 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 foreach (var s in Model.Siblings) {

            
            #line default
            #line hidden
WriteLiteral("                                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 11147), Tuple.Create("\"", 11163)
            
            #line 216 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 11155), Tuple.Create<System.Object, System.Int32>(s.Seqno
            
            #line default
            #line hidden
, 11155), false)
);

            
            #line 216 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                    Write(s.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 216 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                               Write(s.Title);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 217 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n  " +
"                      </div>\r\n                    </li>\r\n                </ul>\r\n" +
"");

            
            #line 223 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                } else {

            
            #line default
            #line hidden
WriteLiteral("                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 226 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.SiteTree.MetaTitle, Piranha.Resources.SiteTree.MetaTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 228 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.SiteTree.MetaTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 229 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 229 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (String.IsNullOrEmpty(Model.SiteTree.MetaTitle)) {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 230 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                      Write(Piranha.Resources.Page.KeywordsNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 231 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </li>\r\n                    <l" +
"i>\r\n");

WriteLiteral("                        ");

            
            #line 235 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.SiteTree.MetaDescription, Piranha.Resources.SiteTree.MetaDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 237 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextAreaFor(m => m.SiteTree.MetaDescription, new { @rows = 5 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 238 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 238 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (String.IsNullOrEmpty(Model.SiteTree.MetaDescription)) {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 239 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                      Write(Piranha.Resources.Page.DescriptionNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 240 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </li>\r\n                </ul>\r" +
"\n");

            
            #line 244 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 248 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 248 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!String.IsNullOrEmpty(Model.Template.Preview.ToString())) {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"grid_3\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box pagetemplate\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 251 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(!Model.IsSite ? Model.Template.Name : Model.SiteTree.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"edit\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 254 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 259 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div>\r\n    <div");

WriteLiteral(" class=\"grid_12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box main-content\"");

WriteLiteral(">\r\n            <table>\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"tools\"");

WriteLiteral(">\r\n                        <ul>\r\n                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 13354), Tuple.Create("\"", 13433)
, Tuple.Create(Tuple.Create("", 13362), Tuple.Create("btn-content", 13362), true)
            
            #line 268 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 13373), Tuple.Create<System.Object, System.Int32>(Model.Action != EditModel.ActionType.SEO ? "active" : ""
            
            #line default
            #line hidden
, 13374), false)
);

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-content\"");

WriteLiteral(">");

            
            #line 268 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                             Write(Piranha.Resources.Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 269 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 269 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 13595), Tuple.Create("\"", 13675)
, Tuple.Create(Tuple.Create("", 13603), Tuple.Create("btn-settings", 13603), true)
            
            #line 270 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 13615), Tuple.Create<System.Object, System.Int32>(Model.Action == EditModel.ActionType.SEO ? "active" : ""
            
            #line default
            #line hidden
, 13616), false)
);

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-settings\"");

WriteLiteral(">");

            
            #line 270 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                               Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 271 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 272 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (Model.Properties.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"btn-properties\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-properties\"");

WriteLiteral(">");

            
            #line 273 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                       Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 274 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 275 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"btn-comments\"");

WriteLiteral(">\r\n");

            
            #line 277 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 277 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  
                                    var count = Model.Comments.Where(c => c.Status == Piranha.Entities.Comment.CommentStatus.New).Count() ;
                                
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span ");

            
            #line 280 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  Write(count == 0 ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(" id=\"comment-notification\" class=\"notification\">");

            
            #line 280 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                          Write(count);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-comments\"");

WriteLiteral(">");

            
            #line 281 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                            </li>\r\n");

            
            #line 283 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 284 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             foreach (var ext in Model.Extensions) {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <a");

WriteLiteral(" href=\"#\"");

            
            #line 286 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(ExtensionManager.Current.GetIconPathByType(ext.Type) != "" ? "style=background-image:url('" + 
                                Url.Content(ExtensionManager.Current.GetIconPathByType(ext.Type)) + "')" : "");

            
            #line default
            #line hidden
WriteLiteral(" data-id=\"pnl-");

            
            #line 287 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                       Write(ExtensionManager.Current.GetInternalIdByType(ext.Type).ToLower());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");

WriteLiteral("                                    ");

            
            #line 288 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(ExtensionManager.Current.GetNameByType(ext.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </a>\r\n                            </li>\r\n");

            
            #line 291 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </td>\r\n                    <td" +
">\r\n                        <div");

WriteLiteral(" id=\"pnl-content\"");

WriteAttribute("class", Tuple.Create(" class=\"", 15420), Tuple.Create("\"", 15507)
, Tuple.Create(Tuple.Create("", 15428), Tuple.Create("main", 15428), true)
, Tuple.Create(Tuple.Create(" ", 15432), Tuple.Create("content-editor", 15433), true)
            
            #line 295 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 15447), Tuple.Create<System.Object, System.Int32>(Model.Action != EditModel.ActionType.SEO ? "" : "hidden"
            
            #line default
            #line hidden
, 15448), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" id=\"regionbuttons\"");

WriteLiteral(" class=\"buttons\"");

WriteLiteral(">\r\n");

            
            #line 298 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 298 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     for (int n = 0; n < Model.Regions.Count; n++) {

            
            #line default
            #line hidden
WriteLiteral("                                        <button");

WriteAttribute("id", Tuple.Create(" id=\"", 15767), Tuple.Create("\"", 15819)
            
            #line 299 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 15772), Tuple.Create<System.Object, System.Int32>(Html.Raw("btn_" + Model.Regions[n].InternalId)
            
            #line default
            #line hidden
, 15772), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 15820), Tuple.Create("\"", 15863)
, Tuple.Create(Tuple.Create("", 15828), Tuple.Create("btn", 15828), true)
            
            #line 299 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               , Tuple.Create(Tuple.Create("", 15831), Tuple.Create<System.Object, System.Int32>(n > 0 ? "" : " active"
            
            #line default
            #line hidden
, 15831), false)
, Tuple.Create(Tuple.Create(" ", 15856), Tuple.Create("region", 15857), true)
);

WriteLiteral(">");

            
            #line 299 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                            Write(Model.Regions[n].Name);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 300 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <button");

WriteLiteral(" id=\"btn_attachments\"");

WriteAttribute("class", Tuple.Create(" class=\"", 16001), Tuple.Create("\"", 16056)
, Tuple.Create(Tuple.Create("", 16009), Tuple.Create("btn", 16009), true)
            
            #line 301 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 16012), Tuple.Create<System.Object, System.Int32>(Model.Regions.Count == 0 ? " active" : ""
            
            #line default
            #line hidden
, 16012), false)
);

WriteLiteral(">");

            
            #line 301 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                    Write(Piranha.Resources.Page.Attachments);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </div>\r\n                              " +
"  <h2");

WriteLiteral(" id=\"section-title\"");

WriteLiteral(">");

            
            #line 303 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Piranha.Resources.Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n");

            
            #line 306 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 306 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 if (Model.Regions.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" id=\"regions\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 308 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Html.EditorFor(m => m.Regions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

            
            #line 310 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" id=\"attachments\"");

WriteLiteral(" ");

            
            #line 311 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Model.Regions.Count > 0 ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 312 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Html.Partial("Partial/Attachments"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n");

            
            #line 316 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 316 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-settings\"");

WriteAttribute("class", Tuple.Create(" class=\"", 16971), Tuple.Create("\"", 17043)
, Tuple.Create(Tuple.Create("", 16979), Tuple.Create("main", 16979), true)
            
            #line 317 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 16983), Tuple.Create<System.Object, System.Int32>(Model.Action == EditModel.ActionType.SEO ? "" : "hidden"
            
            #line default
            #line hidden
, 16984), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 318 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                                    <li>\r\n");

WriteLiteral("                                        ");

            
            #line 322 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 324 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.DropDownListFor(m => m.Page.GroupId, Model.Groups));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                                        ");

            
            #line 325 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.DisabledGroups));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" id=\"disable-groups\"");

WriteLiteral(" class=\"block\"");

WriteLiteral(">\r\n");

            
            #line 327 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 327 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                               var dGroups = Model.Groups.Where(g => g.Value != Guid.Empty.ToString()).ToList() ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                            ");

            
            #line 328 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.Partial("Partial/GroupList", new Piranha.Models.Manager.PageModels.GroupListModel() { 
                                                Groups = Model.DisableGroups, Page = Model.Page }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n                               " +
"     </li>\r\n                                    <li>\r\n");

WriteLiteral("                                        ");

            
            #line 333 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <p>");

            
            #line 334 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      Write(Html.CheckBoxFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 334 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                               Write(Piranha.Resources.Page.HiddenDescription);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                                    </li>\r\n                               " +
"     <li>");

            
            #line 336 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral("> \r\n");

WriteLiteral("                                            ");

            
            #line 338 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.Keywords, new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 339 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 339 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             if (Model.Action == EditModel.ActionType.SEO && String.IsNullOrEmpty(Model.Page.Keywords)) {

            
            #line default
            #line hidden
WriteLiteral("                                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 340 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Piranha.Resources.Page.KeywordsNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 341 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </div>\r\n");

WriteLiteral("                                        ");

            
            #line 343 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n                                    " +
"<li>");

            
            #line 345 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 347 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextAreaFor(m => m.Page.Description, new { @rows = 3, @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 348 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 348 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             if (Model.Action == EditModel.ActionType.SEO && String.IsNullOrEmpty(Model.Page.Description)) {

            
            #line default
            #line hidden
WriteLiteral("                                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 349 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Piranha.Resources.Page.DescriptionNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 350 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </div>\r\n");

WriteLiteral("                                        ");

            
            #line 352 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");

            
            #line 354 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 354 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowController) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 355 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 357 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageController, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Controller) ? Model.Template.Controller : Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                                        ");

            
            #line 358 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");

            
            #line 360 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    ");

            
            #line 361 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowRedirect) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 362 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 364 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageRedirect, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Redirect) ? Model.Template.Redirect : Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                                        ");

            
            #line 365 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");

            
            #line 367 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");

            
            #line 371 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 372 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Properties.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-properties\"");

WriteLiteral(" class=\"main hidden\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 374 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n");

            
            #line 377 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 377 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 for (int n = 0; n < Model.Properties.Count; n++) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 378 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Properties[n], Model.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 379 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 380 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 381 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 382 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 383 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 384 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 385 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 387 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Properties[n].Value));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </li>\r\n");

            
            #line 389 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");

            
            #line 393 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 394 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-comments\"");

WriteLiteral(" class=\"main content-editor hidden\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 396 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner region-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 398 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                           Write(Html.Partial("~/Areas/Manager/Views/Comment/List.cshtml", Model.Comments));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 401 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 402 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"grid_3 hidden\"");

WriteLiteral(">\r\n");

            
            #line 410 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 410 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!Model.Page.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"box expandable\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 412 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Piranha.Resources.Global.Versioning);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div");

WriteLiteral(" class=\"inner optional\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n                <li>");

            
            #line 415 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.LastPublished);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 416 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                Write(Model.Page.LastPublished > DateTime.MinValue ? Model.Page.LastPublished.ToShortDateString() : "");

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");

            
            #line 417 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Published);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 418 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                Write(Model.Page.Published > DateTime.MinValue ? Model.Page.Published.ToShortDateString() : "");

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");

            
            #line 419 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">");

            
            #line 419 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Model.Page.Updated.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");

            
            #line 420 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">");

            
            #line 420 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Model.Page.Created.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n");

            
            #line 424 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 426 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Foot", () => {

WriteLiteral("\r\n <div");

WriteLiteral(" id=\"boxContent\"");

WriteLiteral(" class=\"floatbox\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bg\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(" style=\"min-width: 510px;min-height:260px;\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n");

});

        }
    }
}
#pragma warning restore 1591
