#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Content
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Content/Popup.cshtml")]
    public partial class Popup : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.ContentModels.PopupModel>
    {
        public Popup()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
  
    Layout = "";
    var first = true ;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"box-tabs\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"selected\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#attach-existing\"");

WriteLiteral(">Choose existing</a></li>\r\n        <li");

WriteLiteral(" class=\"hidden\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#attach-new\"");

WriteLiteral(">Upload new</a></li>\r\n    </ul>\r\n    <a");

WriteLiteral(" class=\"close-btn right\"");

WriteLiteral(" data-id=\"boxContent\"");

WriteLiteral("></a>\r\n    <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n</div>\r\n<div");

WriteLiteral(" id=\"attach-existing\"");

WriteAttribute("class", Tuple.Create(" class=\"", 438), Tuple.Create("\"", 515)
, Tuple.Create(Tuple.Create("", 446), Tuple.Create("inner", 446), true)
, Tuple.Create(Tuple.Create(" ", 451), Tuple.Create("gallery", 452), true)
            
            #line 14 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
, Tuple.Create(Tuple.Create(" ", 459), Tuple.Create<System.Object, System.Int32>(Model.Content.Count > 12 ? "gallery-compressed" : ""
            
            #line default
            #line hidden
, 460), false)
);

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
     foreach (var content in Model.Content) {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 578), Tuple.Create("\"", 646)
, Tuple.Create(Tuple.Create("", 586), Tuple.Create("gallery-item", 586), true)
            
            #line 16 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
, Tuple.Create(Tuple.Create(" ", 598), Tuple.Create<System.Object, System.Int32>(Model.Content.Count > 12 ? "compressed" : ""
            
            #line default
            #line hidden
, 599), false)
);

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
             if (first && content.ParentId != Guid.Empty) {

            
            #line default
            #line hidden
WriteLiteral("            <img");

WriteLiteral(" class=\"folder\"");

WriteLiteral(" data-id=\"");

            
            #line 18 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                    Write(content.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("src", Tuple.Create(" src=\"", 764), Tuple.Create("\"", 834)
            
            #line 18 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
, Tuple.Create(Tuple.Create("", 770), Tuple.Create<System.Object, System.Int32>(Url.Content("~/areas/manager/content/img/ico-folder-up-96.png")
            
            #line default
            #line hidden
, 770), false)
);

WriteLiteral(" />\r\n");

            
            #line 19 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("            <img");

            
            #line 20 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
            Write(content.IsFolder ? " class=folder" : (!content.IsImage ? " class=document" : ""));

            
            #line default
            #line hidden
WriteLiteral(" data-id=\"");

            
            #line 20 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                                                        Write(content.Id);

            
            #line default
            #line hidden
WriteLiteral("\" src=\"");

            
            #line 20 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                                                                          Write(Url.GetThumbnailUrl(content.Id, 96));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");

            
            #line 20 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                                                                                                                       Write(content.AlternateText);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");

            
            #line 20 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                                                                                                                                                    Write(content.AlternateText);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");

            
            #line 21 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <p><small>");

            
            #line 22 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                 Write(content.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</small></p>\r\n        </div>\r\n");

            
            #line 24 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
        first = false ;
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
