#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Manager.PageType
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/PageType/Edit.cshtml")]
    public class Edit : Piranha.Manager.Templates.PageTypeEdit
    {

                // Resolve package relative syntax
                // Also, if it comes from a static embedded resource, change the path accordingly
                public override string Href(string virtualPath, params object[] pathParts) {
                    virtualPath = ApplicationPart.ProcessVirtualPath(GetType().Assembly, VirtualPath, virtualPath);
                    return base.Href(virtualPath, pathParts);
                }
        public Edit()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



            
            #line 4 "..\..\PageType\Edit.cshtml"
  
    Layout = "~/Manager/Shared/_Layout.cshtml" ;


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 8 "..\..\PageType\Edit.cshtml"
                                   Write(Href("~/manager/content/js/jquery.form.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 9 "..\..\PageType\Edit.cshtml"
                                   Write(Href("~/manager/content/js/jquery.template.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 10 "..\..\PageType\Edit.cshtml"
                                   Write(Href("~/manager/content/js/jquery.regiontemplate.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 11 "..\..\PageType\Edit.cshtml"
                                   Write(Href("~/manager/content/js/ext/json2.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 12 "..\..\PageType\Edit.cshtml"
                                   Write(Href("~/manager/content/Js/ext/jquery.equalheights.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\">\r\n        /**\r\n         * This va" +
"r is needed by the regiontemplate script.\r\n         */\r\n        var templateid =" +
" \'");


            
            #line 17 "..\..\PageType\Edit.cshtml"
                     Write(Model.Template.Id);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\r\n        $(document).ready(function () {\r\n            $(\'.first-row .box\').e" +
"qualHeights();\r\n        });\r\n    </script>\r\n");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a class=\"save submit\">");


            
            #line 28 "..\..\PageType\Edit.cshtml"
                                  Write(Piranha.Manager.Resources.Toolbar.Save);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 29 "..\..\PageType\Edit.cshtml"
                    Write(Href("~/manager/pagetype/edit/delete" + Model.Template.Id));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\" title=\"\">");


            
            #line 29 "..\..\PageType\Edit.cshtml"
                                                                                                         Write(Piranha.Manager.Resources.Toolbar.Delete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 30 "..\..\PageType\Edit.cshtml"
                    Write(Href("~/manager/pagetype"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 30 "..\..\PageType\Edit.cshtml"
                                                              Write(Piranha.Manager.Resources.Toolbar.Back);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 31 "..\..\PageType\Edit.cshtml"
                    Write(Href("~/manager/pagetype/edit/" + Model.Template.Id));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 31 "..\..\PageType\Edit.cshtml"
                                                                                           Write(Piranha.Manager.Resources.Toolbar.Reload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n" +
"");


});

WriteLiteral("\r\n\r\n<form>\r\n    <div>\r\n        ");


            
            #line 40 "..\..\PageType\Edit.cshtml"
   Write(Form.Action("Save"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 41 "..\..\PageType\Edit.cshtml"
   Write(Form.HiddenFor(m => m.Template.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"first-row\">\r\n        <div class=\"grid_9\">\r\n        " +
"    <div class=\"box expandable\">\r\n                <div class=\"title\"><h2>");


            
            #line 46 "..\..\PageType\Edit.cshtml"
                                  Write(Piranha.Manager.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                <div class=\"inner\">\r\n                    <ul class=\"" +
"form\">\r\n                        <li>");


            
            #line 49 "..\..\PageType\Edit.cshtml"
                       Write(Form.LabelFor(m => m.Template.Name, Piranha.Manager.Resources.Global.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"input\">\r\n                              " +
"  ");


            
            #line 51 "..\..\PageType\Edit.cshtml"
                           Write(Form.TextBoxFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            ");


            
            #line 52 "..\..\PageType\Edit.cshtml"
                       Write(Form.ValidationMessageFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </li>\r\n                        <li>");


            
            #line 54 "..\..\PageType\Edit.cshtml"
                       Write(Form.LabelFor(m => m.Template.ViewTemplate, Piranha.Manager.Resources.PageType.ViewTemplate));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"right\">\r\n                              " +
"  ");


            
            #line 56 "..\..\PageType\Edit.cshtml"
                           Write(Form.CheckBoxFor(m => m.Template.ShowViewTemplate));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"input short\">\r\n                  " +
"              ");


            
            #line 58 "..\..\PageType\Edit.cshtml"
                           Write(Form.TextBoxFor(m => m.Template.ViewTemplate, 
                                    new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </li>\r\n                        <li>");


            
            #line 61 "..\..\PageType\Edit.cshtml"
                       Write(Form.LabelFor(m => m.Template.ViewRedirect, Piranha.Manager.Resources.PageType.ViewRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"right\">\r\n                              " +
"  ");


            
            #line 63 "..\..\PageType\Edit.cshtml"
                           Write(Form.CheckBoxFor(m => m.Template.ShowViewRedirect));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div class=\"input short\">\r\n                  " +
"              ");


            
            #line 65 "..\..\PageType\Edit.cshtml"
                           Write(Form.TextBoxFor(m => m.Template.ViewRedirect, 
                                    new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </li>\r\n                        <li>");


            
            #line 68 "..\..\PageType\Edit.cshtml"
                       Write(Form.LabelFor(m => m.Template.Description, Piranha.Manager.Resources.Global.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"input\">\r\n                              " +
"  ");


            
            #line 70 "..\..\PageType\Edit.cshtml"
                           Write(Form.TextAreaFor(m => m.Template.Description, 
                                    new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </li>\r\n                    </ul>\r\n               " +
" </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"grid_3\">\r\n     " +
"       <div class=\"box pagetemplate\">\r\n                <div class=\"title\"><h2>");


            
            #line 79 "..\..\PageType\Edit.cshtml"
                                  Write(Piranha.Manager.Resources.PageType.Preview);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                <div class=\"inner\">\r\n                    <div class=" +
"\"edit\">\r\n                        ");


            
            #line 82 "..\..\PageType\Edit.cshtml"
                   Write(Model.Template.Preview.Html());

            
            #line default
            #line hidden
WriteLiteral(@"
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class=""grid_12"">
            <div class=""box main-content"">
                <table>
                    <tr>
                        <td class=""tools"">
                            <ul>
                                <li class=""btn-regions active""><a href=""#"" data-id=""pnl-regions"">Regions</a></li>
                                <li class=""btn-properties""><a href=""#"" data-id=""pnl-properties"">Properties</a></li>
                                <li class=""btn-preview""><a href=""#"" data-id=""pnl-preview"">Preview</a></li>
                            </ul>
                        </td>
                        <td>
                            <div id=""pnl-regions"" class=""main"">
                                <div class=""title""><h2>Regions</h2></div>
                                <div class=""inner"">
                                    <table class=""list"">
                                        <thead>
                                            <tr>
                                                <th>");


            
            #line 107 "..\..\PageType\Edit.cshtml"
                                               Write(Piranha.Resources.Global.Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                                <th>");


            
            #line 108 "..\..\PageType\Edit.cshtml"
                                               Write(Piranha.Resources.Global.InternalId);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                                <th>");


            
            #line 109 "..\..\PageType\Edit.cshtml"
                                               Write(Piranha.Resources.Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                                <th></th>\r\n               " +
"                             </tr>\r\n                                        </th" +
"ead>\r\n                                        <tbody>\r\n");


            
            #line 114 "..\..\PageType\Edit.cshtml"
                                             for (int n = 0; n < Model.Template.RegionTemplates.Count; n++) {

            
            #line default
            #line hidden
WriteLiteral("                                            <tr>\r\n                               " +
"                 <td class=\"form\">\r\n                                            " +
"        <span>");


            
            #line 117 "..\..\PageType\Edit.cshtml"
                                                     Write(Model.Template.RegionTemplates[n].Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                                    <div class=\"input hi" +
"dden\">\r\n                                                        ");


            
            #line 119 "..\..\PageType\Edit.cshtml"
                                                   Write(Form.TextBoxFor(m => m.Template.RegionTemplates[n].Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                                    ");


            
            #line 120 "..\..\PageType\Edit.cshtml"
                                               Write(Form.ValidationMessageFor(m => m.Template.RegionTemplates[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </td>\r\n                        " +
"                        <td class=\"form\">\r\n                                     " +
"               <span>");


            
            #line 123 "..\..\PageType\Edit.cshtml"
                                                     Write(Model.Template.RegionTemplates[n].InternalId);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                                    <div class=\"input hi" +
"dden\">\r\n                                                        ");


            
            #line 125 "..\..\PageType\Edit.cshtml"
                                                   Write(Form.TextBoxFor(m => m.Template.RegionTemplates[n].InternalId));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                                    <div style=\"position:" +
" relative\">\r\n                                                        ");


            
            #line 127 "..\..\PageType\Edit.cshtml"
                                                   Write(Form.ValidationMessageFor(m => m.Template.RegionTemplates[n].InternalId));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                                </td>\r\n                  " +
"                              <td>\r\n                                            " +
"        <span class=\"readonly\">");


            
            #line 130 "..\..\PageType\Edit.cshtml"
                                                                      Write(Piranha.Extend.ExtensionManager.GetExtensionNameByType(Model.Template.RegionTemplates[n].Type));

            
            #line default
            #line hidden
WriteLiteral(@"</span>
                                                </td>
                                                <td class=""buttons four"">
                                                    <a class=""icon up marg""></a>
                                                    <a class=""icon down marg""></a>
                                                    <a class=""icon edit marg""></a>
                                                    <a class=""icon delete""></a>
                                                    <div class=""hidden"">
                                                        ");


            
            #line 138 "..\..\PageType\Edit.cshtml"
                                                   Write(Form.HiddenFor(m => m.Template.RegionTemplates[n].Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                        ");


            
            #line 139 "..\..\PageType\Edit.cshtml"
                                                   Write(Form.HiddenFor(m => m.Template.RegionTemplates[n].Seqno, new { @class = "region-seqno" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                        ");


            
            #line 140 "..\..\PageType\Edit.cshtml"
                                                   Write(Form.HiddenFor(m => m.Template.RegionTemplates[n].Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                        ");


            
            #line 141 "..\..\PageType\Edit.cshtml"
                                                   Write(Form.HiddenFor(m => m.Template.RegionTemplates[n].Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                    </div>\r\n                   " +
"                             </td> \r\n                                           " +
" </tr>\r\n");


            
            #line 145 "..\..\PageType\Edit.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral(@"                                            <tr class=""dark"">
                                                <td class=""form"">
                                                    <div class=""input"">
                                                        <input type=""text"" id=""newregionName"" placeholder=""");


            
            #line 149 "..\..\PageType\Edit.cshtml"
                                                                                                      Write(Piranha.Resources.Global.Name);

            
            #line default
            #line hidden
WriteLiteral(@""" /></div>
                                                </td>
                                                <td class=""form"">
                                                    <div class=""input"">
                                                        <input type=""text"" id=""newregionInternalId"" placeholder=""");


            
            #line 153 "..\..\PageType\Edit.cshtml"
                                                                                                            Write(Piranha.Resources.Global.InternalId);

            
            #line default
            #line hidden
WriteLiteral(@""" /></div>
                                                </td>
                                                <td class=""form"">
                                                    <div class=""input"">
                                                        ");


            
            #line 157 "..\..\PageType\Edit.cshtml"
                                                   Write(Html.DropDownList("newregionType", "", Model.RegionTypes, new { @placeholder = Piranha.Resources.Global.Type }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                                </td>\r\n                  " +
"                              <td class=\"buttons four\">\r\n                       " +
"                             <button id=\"btnAddRegion\" class=\"btn marg-big\">");


            
            #line 160 "..\..\PageType\Edit.cshtml"
                                                                                              Write(Piranha.Resources.Global.Add);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                            <div id=""pnl-properties"" class=""main hidden"">
                                <div class=""title""><h2>Properties</h2></div>
                                <div class=""inner"">
                                    <table class=""list"">
                                        <thead>
                                            <tr>
                                                <th>");


            
            #line 174 "..\..\PageType\Edit.cshtml"
                                               Write(Piranha.Resources.Global.Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                                <th>");


            
            #line 175 "..\..\PageType\Edit.cshtml"
                                               Write(Piranha.Resources.Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                                <th></th>\r\n               " +
"                             </tr>\r\n                                        </th" +
"ead>\r\n                                        <tbody id=\"properties\">\r\n");


            
            #line 180 "..\..\PageType\Edit.cshtml"
                                             foreach (var prop in Model.Template.Properties) {

            
            #line default
            #line hidden
WriteLiteral("                                            <tr>\r\n                               " +
"                 <td class=\"form\"><span>");


            
            #line 182 "..\..\PageType\Edit.cshtml"
                                                                  Write(prop);

            
            #line default
            #line hidden
WriteLiteral(@"</span></td>
                                                <td class=""form""><span>String</span></td>
                                                <td class=""buttons three"">
                                                    <a class=""icon up marg""></a>
                                                    <a class=""icon down marg""></a>
                                                    <a class=""icon delete remove-region""></a>
                                                </td>
                                            </tr>
");


            
            #line 190 "..\..\PageType\Edit.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral(@"                                            <tr class=""dark"">
                                                <td class=""form"" colspan=""2"">
                                                    <div class=""input"">
                                                        <input type=""text"" id=""po_name"" placeholder=""");


            
            #line 194 "..\..\PageType\Edit.cshtml"
                                                                                                Write(Piranha.Resources.Template.PropertyPlaceholder);

            
            #line default
            #line hidden
WriteLiteral("\" /></div>\r\n                                                </td>\r\n              " +
"                                  <td class=\"buttons three\">\r\n                  " +
"                                  <button id=\"po_add\" class=\"btn marg-big\">");


            
            #line 197 "..\..\PageType\Edit.cshtml"
                                                                                        Write(Piranha.Resources.Global.Add);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>

                                    <div id=""region_data""></div>
                                    <ul id=""properties_old"" class=""list buttons"">
");


            
            #line 205 "..\..\PageType\Edit.cshtml"
                                         foreach (var property in Model.Template.Properties) {

            
            #line default
            #line hidden
WriteLiteral("                                        <li><span>");


            
            #line 206 "..\..\PageType\Edit.cshtml"
                                             Write(property);

            
            #line default
            #line hidden
WriteLiteral("</span><button class=\"btn delete right remove-region\"></button></li>\r\n");


            
            #line 207 "..\..\PageType\Edit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </ul>\r\n                                    <d" +
"iv class=\"input\">\r\n                                        <input id=\"po_name_ol" +
"d\" type=\"text\" placeholder=\"");


            
            #line 210 "..\..\PageType\Edit.cshtml"
                                                                                    Write(Piranha.Resources.Template.PropertyPlaceholder);

            
            #line default
            #line hidden
WriteLiteral("\" /></div>\r\n                                    <button id=\"po_add_old\" class=\"bt" +
"n right\">");


            
            #line 211 "..\..\PageType\Edit.cshtml"
                                                                         Write(Piranha.Resources.Global.Add);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                                    <div class=""clear""></div>
                                </div>
                            </div>
                            <div id=""pnl-preview"" class=""main hidden"">
                                <div class=""title""><h2>Preview</h2></div>
                                <div class=""inner"">
                                    <ul class=""form"">               
                                        <li>");


            
            #line 219 "..\..\PageType\Edit.cshtml"
                                       Write(Form.LabelFor(m => m.Template.Preview, Piranha.Manager.Resources.PageType.Preview));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <div class=\"input\">\r\n              " +
"                                  ");


            
            #line 221 "..\..\PageType\Edit.cshtml"
                                           Write(Form.TextAreaFor(m => m.Template.Preview, new { @rows = 8} ));

            
            #line default
            #line hidden
WriteLiteral(@"</div>
                                        </li>                
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</form>");


        }
    }
}
#pragma warning restore 1591
